// import { LootObj } from './lootclass';

export const individualZeroFour = [
    { pc: '5d6', pp: '', pe: '', po: '', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '4d6', pe: '', po: '', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '3d6', po: '', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '3d6', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '1d6', gemArt: '', magicItems: '' }
];
export const individualFiveTen = [
    { pc: '4d6x100', pp: '', pe: '1d6x10', po: '', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '6d6x10', pe: '', po: '', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '1d6x100', po: '', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '4d6x10', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '2d6x10', pl: '', gemArt: '', magicItems: '' }
];
export const individualElevenSixteen = [
    { pc: '', pp: '4d6x100', pe: '', po: '1d6x100', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '1d6x100', po: '1d6x100', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '2d6x100', pl: '1d6x10', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '2d6x100', pl: '2d6x10', gemArt: '', magicItems: '' }
];
export const individualSeventeenPlus = [
    { pc: '', pp: '', pe: '2d6x1000', po: '8d6x100', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '1d6x1000', pl: '1d6x100', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '1d6x1000', pl: '2d6x100', gemArt: '', magicItems: '' }
];
export const hoardZeroFour = [
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d6x10gems', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x25art', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d6x50gems', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d6x10gems', magicItems: '1d6xMagItemA' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x25art', magicItems: '1d6xMagItemA' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d6x50gems', magicItems: '1d6xMagItemA' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d6x10gems', magicItems: '1d6xMagItemB' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x25art', magicItems: '1d6xMagItemB' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d6x50gems', magicItems: '1d6xMagItemB' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d6x10gems', magicItems: '1d6xMagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x25art', magicItems: '1d6xMagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d6x50gems', magicItems: '1d6xMagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x25art', magicItems: '1d6xMagItemF' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d6x50gems', magicItems: '1d6xMagItemF' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x25art', magicItems: '1d6xMagItemG' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d6x50gems', magicItems: '1d6xMagItemG' }
];
export const hoardFiveTen = [
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x25art', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x50gems', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x100gems', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x25art', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x25art', magicItems: '1d6xMagItemA' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x50gems', magicItems: '1d6xMagItemA' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x100gems', magicItems: '1d6xMagItemA' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '1d6xMagItemA' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x25art', magicItems: '1d4xMagItemB' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x50gems', magicItems: '1d4xMagItemB' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x100gems', magicItems: '1d4xMagItemB' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '1d4xMagItemB' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x25art', magicItems: '1d4xMagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x50gems', magicItems: '1d4xMagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x100gems', magicItems: '1d4xMagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '1d4xMagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x25art', magicItems: '1d1xMagItemD' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x50gems', magicItems: '1d1xMagItemD' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x100gems', magicItems: '1d1xMagItemD' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '1d1xMagItemD' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x25art', magicItems: '1d4xMagItemF' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x50gems', magicItems: '1d4xMagItemF' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x100gems', magicItems: '1d4xMagItemF' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '1d4xMagItemF' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x100gems', magicItems: '1d4xMagItemG' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '1d6xMagItemG' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x100gems', magicItems: '1d1xMagItemH' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '1d1xMagItemH' }
];
export const hoardElevenSixteen = [
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x750art', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x500gems', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '1d4xMagItemA&1d6xMagItemB' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x750art', magicItems: '1d4xMagItemA&1d6xMagItemB' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x500gems', magicItems: '1d4xMagItemA&1d6xMagItemB' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '1d4xMagItemA&1d6xMagItemB' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '1d6xMagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x750art', magicItems: '1d6xMagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x500gems', magicItems: '1d6xMagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '1d6xMagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '1d4xMagItemD' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x750art', magicItems: '1d4xMagItemD' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x500gems', magicItems: '1d4xMagItemD' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '1d4xMagItemD' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '1d1MagItemE' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x750art', magicItems: '1d1MagItemE' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x500gems', magicItems: '1d1MagItemE' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '1d1MagItemE' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '1d1MagItemF&1d4xMagItemG' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x750art', magicItems: '1d1MagItemF&1d4xMagItemG' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x500gems', magicItems: '1d1MagItemF&1d4xMagItemG' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '1d1MagItemF&1d4xMagItemG' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '1d4xMagItemH' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x750art', magicItems: '1d4xMagItemH' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x500gems', magicItems: '1d4xMagItemH' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '1d4xMagItemH' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '2d4x250art', magicItems: '1d1MagItemI' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x500gems', magicItems: '1d1MagItemI' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '1d1MagItemI' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '1d1MagItemI' }
];
export const hoardSeventeenPlus = [
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '', magicItems: '' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '1d8MagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d10x2500art', magicItems: '1d8MagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d4x7500art', magicItems: '1d8MagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d8x5000gems', magicItems: '1d8MagItemC' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '1d6MagItemD' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1dl0x2500art', magicItems: '1d6MagItemD' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d4x7500art', magicItems: '1d6MagItemD' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d8x5000gems', magicItems: '1d6MagItemD' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '1d6MagItemE' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d10x2500art', magicItems: 'd6MagItemE' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d4x7500art', magicItems: '1d6MagItemE' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d8x5000gems', magicItems: '1d6MagItemE' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '1d4MagItemG' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d10x2500art', magicItems: '1d4MagItemG' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d4x7500art', magicItems: 'd4MagItemG' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d8x5000gems', magicItems: '1d4MagItemG' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '1d4MagItemH' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d10x2500art', magicItems: '1d4MagItemH' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d4x7500art', magicItems: '1d4MagItemH' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d8x5000gems', magicItems: '1d4MagItemH' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '3d6x1000gems', magicItems: '1d4MagItemI' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d10x2500art', magicItems: '1d4MagItemI' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d4x7500art', magicItems: '1d1MagItemF&1d4MagItemG' },
    { pc: '', pp: '', pe: '', po: '', pl: '', gemArt: '1d8x5000gems', magicItems: '1d4MagItemI' }
];
export const gems10gp = [
    "Azurita","Ágata malhada","Quartzo azul","Ágata ocular","Hematita","Lápis lazúli","Malaquita","Ágata musgo","Obsidiana","Rodocrosita","Olho de tigre","Turquesa"
];
export const gems50gp = [
    "Pedra de sangue","Cornalina","Calcedônia","Crisoprásio","Citrina","Jaspe","Pedra lunar","Ônix","Quartzo","Sardônica","Quartzo rosa estrela","Zircônio"
];
export const gems100gp = [
    "Âmbar","Ametista","Crisoberilo","Coral","Granada","Jade","Jato","Pérola","Espinela","Turmalina"
];
export const gems500gp = [
    "Alexandrita","Água-marinha","Pérola negra","Espinela azul","Peridoto","Topázio"
];
export const gems1000gp = [
    "Opala negra","Safira azul","Esmeralda","Opala de fogo","Opala","Rubi estrela","Safira estrela","Safira amarela"
];
export const gems5000gp = [
    "Safira negra","Diamante","Jacinto","Rubi"
];
export const art25gp = [
];
export const art250gp = [
];
export const art750gp = [
];
export const art2500gp = [
];
export const art7500gp = [
];

export const magTableA = ["Poção de cura", "Pergaminho de magia (truque)", "Poção de escalar", "Pergaminho de magia (1° nível)", "Pergaminho de magia (2° nível)", "Poção de cura maior", "Mochila de carga"];
export const magTableB = [
    "Poção de cura maior","Poção de sopro de fogo","Poção de resistência","Munição +1","Poção de amizade animal","Poção de força do gigante da colina","Poção de aumentar","Poção de respirar na água","Pergaminho de magia (2° nível)","Pergaminho de magia (3° nível)","Mochila de carga","Unguento de Keoghtom","Óleo escorregadio","Pó do desaparecimento","Pó da seca","Pó de espirrar e tossir","Gema elemental","Filtro do amor","Jarro de alquimia","Capa de respirar na água","Manto da arraia","Globo de fluxo","Óculos noturnos","Elmo de compreensão de idiomas","Bastão imóvel","Lanterna de revelação","Armadura do marinheiro","Armadura de mitral","Poção de envenenamento","Anel de natação","Robe dos itens úteis","Corda de escalada","Sela do cavaleiro","Varinha de detectar magia","Varinha de segredos"
];
export const magTableC = [
    "Poção de cura maior","Pergaminho de magia (4° nível)","Munição +2","Poção de clarividência","Poção de encolher","Poção de forma gasosa","Poção de força do gigante do gelo","Poção de força do gigante de pedra","Poção de heroísmo","Poção de invulnerabilidade","Poção de ler mentes","Pergaminho de magia (5° nível)","Elixir de saúde","Óleo de forma etérea","Poção de força do gigante do fogo","Pena de Quaal","Pergaminho de proteção","Saco de feijões","Contas de força","Carrilhão de abertura","Decantador de água infinita","Olhos de visão momentânea","Barco dobrável","Sacola prestativa de Heward","Ferraduras da velocidade","Colar de bolas de fogo","Periapto de saúde","Pedras de mensagem"
];
export const magTableD = [
    "Potion of supreme healing",
    "Potion of invisibility",
    "Potion of speed",
    "Spell scroll (6thlevel)",
    "Spell scroll (7thlevel)",
    "Ammunition, +3",
    "Oil of sharpness",
    "Potion of flying",
    "Potion of cloud giant strength",
    "Potion of longevity",
    "Potion of vitality",
    "Spell scroll (8thlevel)",
    "Horseshoes of a zephyr",
    "Nolzur's marvelous pigments",
    "Bag of devouring",
    "Portable hole"
];
export const magTableE = [
    "Spell scroll (8thlevel)",
    "Potion of storm giant strength",
    "Poti on of supreme healing",
    "Spell scroll (9st level)",
    "Universal solvent",
    "Arrow of slaying",
    "Sovereign glue"
];
export const magTableF = [
    "Weapon, +1",
    "Shield,+ 1",
    "Sentinel shield",
    "Amulet of proof against detection and location",
    "Boots of elvenkind",
    "Boots of striding and springing",
    "Bracers of archery",
    "Brooch of shielding",
    "Broom of flying",
    "Cloak of elvenkind",
    "Cloak of protection",
    "Gauntlets of ogre power",
    "Hat of disguise",
    "Javelin of lightning",
    "Pearl of power",
    "Rod of the pact keeper, + 1",
    "Slippers of spider climbing",
    "Staff of the adder",
    "Staff of the python",
    "Sword of vengeance",
    "Trident of fish command",
    "Wand of magic missiles",
    "Wand of the war mage, + 1",
    "Wand of web",
    "Weapon of warning",
    "Adamantine armor (chain mail)",
    "Adamantine armor (chain shirt)",
    "Adamantine armor (scale mail)",
    "Bag of tricks (gray)",
    "Bag of tricks (rust)",
    "Bag of tricks (tan)",
    "Boots of the winterlands",
    "Circlet of blasting",
    "Deck of illusions",
    "Eversmoking bottle",
    "Eyes of charming",
    "Eyes of the eagle",
    "Figurine of wondrous power (silver raven)",
    "Gem of brightness",
    "Gloves of missile snaring",
    "Gloves of swimming and climbing",
    "Gloves of thievery",
    "Headband of intellect",
    "Helm of telepathy",
    "Instrument of the bards (Doss lute)",
    "Instrument of the bards (Fochlucan bandore)",
    "Instrument of the bards (Mac-Fuimidh cittern)",
    "Medallion of thoughts",
    "Necklace of adaptation",
    "Periapt of wound closure",
    "Pipes of haunting",
    "Pipes of the sewers",
    "Ring of jumping",
    "Ring of mind shielding",
    "Ring of warmth",
    "Ring of water walking",
    "Quiver of Ehlonna",
    "Stone of good luck",
    "Wind fan",
    "Winged boots"
];
export const magTableG = [
    "Weapon, +2",
    "Figurine of wondrous power (roll d8)",
    "Adamantine armor (breastplate)",
    "Adamantine armor (splint)",
    "Amulet of health",
    "Armor of vulnerability",
    "Arrow-catching shield",
    "Belt of dwarvenkind",
    "Belt of hill giant strength",
    "Berserker axe",
    "Boots of levitation",
    "Boots of speed",
    "Bowl of commanding water elementals",
    "Bracers of defense",
    "Brazier of commanding fire elementals",
    "Cape of the mountebank",
    "Censer of controlling air elementals",
    "Armor, +1 chain mail",
    "Armor of resistance (chain mail)",
    "Armor of resistance (chain shirt)",
    "Armor,+ 1 chain shirt",
    "Cloak of displacement",
    "Cloak of the bat",
    "Cube of force",
    "Daern's instant fortress",
    "Dagger of venom",
    "Dimensional shackles",
    "Dragon slayer",
    "Elven chain",
    "Flame tongue",
    "Gem of seeing",
    "Giant slayer",
    "Clamoured studded leather",
    "Helm of teleportation",
    "Horn of blasting",
    "Horn of Valhalla (silver or brass)",
    "Instrument of the bards (Canaithmandolin)",
    "Instrument ofthe bards (Cii lyre)",
    "loun stone (awareness)",
    "loun stone (protection)",
    "loun stone (reserve)",
    "loun stone (sustenance)",
    "Iron bands of Bilarro",
    "Armor, + 1 leather",
    "Armor of resistance (leather)",
    "Mace of disruption",
    "Mace of smiting",
    "Mace of terror",
    "Mantle of spell resistance",
    "Necklace of prayer beads",
    "Periapt of proof against poison",
    "Ring of animal influence",
    "Ring of evasion",
    "Ring of feather falling",
    "Ring of free action",
    "Ring of protection",
    "Ring of resistance",
    "Ring of spell storing",
    "Ring of the ram",
    "Ring of X-ray vision",
    "Robe of eyes",
    "Rod of rulership",
    "Rod of the pact keeper, +2",
    "Rope of entanglement",
    "Armor, +1 scale mail",
    "Armor of resistance (scale mail)",
    "Shield, +2",
    "Shield of missile attraction",
    "Staff of charming",
    "Staff of healing",
    "Staff of swarming insects",
    "Staff of the woodlands",
    "Staff of withering",
    "Stone of controlling earthelementals",
    "Sun blade",
    "Sword of life stealing",
    "Sword of wounding",
    "Tentacle rod",
    "Vicious weapon",
    "Wand of binding",
    "Wand of enemy detection",
    "Wand of fear",
    "Wand of fireballs",
    "Wand of lightning bolts",
    "Wand of paralysis",
    "Wand of the war mage, +2",
    "Wand of wonder",
    "Wings of flying",
];
export const magTableH = [
    "Weapon, +3",
"Amulet of the planes",
"Carpet of flying",
"Crystal ball (very rare version)",
"Ring of regeneration",
"Ring of shooting stars",
"Ring of telekinesis",
"Robe of scintillating colors",
"Robe of stars",
"Rod of absorption",
"Rod of alertness",
"Rod of security",
"Rod of the pact keeper, +3",
"Scimitar of speed",
"Shield, +3",
"Staff of fire",
"Staff of frost",
"Staff of power",
"Staff of striking",
"Staff of thunder and lightning",
"Sword of sharpnes",
"Wand of polymorph",
"Wand of the war mage, + 3",
"Adamantine armor (half plate)",
"Adamantine armor (plate)",
"Animated shield",
"Belt of fire giant strength",
"Belt of frost (or stone) giant strength",
"Armor, + 1 breastplate",
"Armor of resistance (breastplate)",
"Candle of invocation",
"Armor, +2 chain mail",
"Armor, +2 chain shirt",
"Cloak of arachnida",
"Dancing sword",
"Demon armor",
"Dragon scale mail",
"Dwarven plate",
"Dwarven thrower",
"Efreeti bottle",
"Figurine of wondrous power (obsidian steed)",
"Frost brand",
"Helm of brilliance",
"Horn ofValhalla (bronze)",
"Instrument of the bards (Anstruthharp)",
"loun stone (absorption)",
"loun stone (agility)",
"loun stone (fortitude)",
"loun stone (insight)",
"loun stone (intellect)",
"loun stone (leadership)",
"loun stone (strength)",
"Armor, +2 leather",
"Manual of bodily health",
"Manual of gainful exercise",
"Manual of golems",
"Manual of quickness of action",
"Mirror of life trapping",
"Nine lives stealer",
"Oathbow",
"Armor, +2 scale mail",
"Spellguard shield",
"Armor, + 1 splint",
"Armor of resistance (splint)",
"Armor, + 1 studded leather",
"Armor of resistance (studded leather)",
"Tome of clear thought",
"Tome of leadership and influence",
"Tome of understanding"
];
export const magTableI = [
    "Defender",
"Hammer of thunderbolts",
"Luck Blade",
"Sword of answering",
"Holy avenger",
"Ring of djinni summoning",
"Ring of invisibility",
"Ring of spell turning",
"Rod of lordly might",
"Vorpal sword",
"Belt of cloud giant strength",
"Armor, +2 breastplate",
"Armor, +3 chain mail",
"Armor, +3 chain shirt",
"Cloak of invisibility",
"Crystal ball (legendary version)",
"Armor, + 1 half plate",
"Iron flask",
"Armor, +3 leather",
"Armor, +1 plate",
"Robe of the archmagi",
"Rod of resurrection",
"Armor, +1 scale mail",
"Scarab of protection",
"Armor, +2 splint",
"Armor, +2 studded leather",
"Well of many worlds",
"Magic armor (roll dl2)",
"Apparatus of Kwalish",
"Armor of invulnerability",
"Belt of storm giant strength",
"Cubic gate",
"Deck of many things",
"Efreeti chain",
"Armor of resistance (half plate)",
"Horn ofValhalla (iron)",
"Instrument of the bards (OIIamh harp)",
"loun stone (greater absorption)",
"loun stone (mastery)",
"loun stone (regeneration)",
"Plate armor of etherealness",
"Plate armor of resistance",
"Ring of air elemental command",
"Ring of earthelemental command",
"Ring of fire elemental command",
"Ring of three wishes",
"Ring of water elemental command",
"Sphere of annihilation",
"Talisman of pure good",
"Talisman of the sphere",
"Talisman of ultimate evil",
"Tome of the stilled tongue"
];
