

export const individual1=[{piece1:{quant:5,sides:6,type:"Peças de Cobre",multiply:1}},{piece1:{quant:4,sides:6,type:"Peças de Prata",multiply:1}},{piece1:{quant:3,sides:6,type:"Peças de Electrum",multiply:1}},{piece1:{quant:3,sides:6,type:"Peças de Ouro",multiply:1}},{piece1:{quant:1,sides:6,type:"Peças de Platina",multiply:1}}];

export const individual2=[{piece1:{quant:4,sides:6,type:"Peças de Cobre",multiply:100},piece2:{quant:1,sides:6,type:"Peças de Electrum",multiply:10}},{piece1:{quant:6,sides:6,type:"Peças de Prata",multiply:10},piece2:{quant:2,sides:6,type:"Peças de Ouro",multiply:10}},{piece1:{quant:1,sides:6,type:"Peças de Electrum",multiply:100},piece2:{quant:2,sides:6,type:"Peças de Ouro",multiply:10}},{piece1:{quant:4,sides:6,type:"Peças de Ouro",multiply:10}},{piece1:{quant:2,sides:6,type:"Peças de Ouro",multiply:10},piece2:{quant:3,sides:6,type:"Peças de Platina",multiply:1}}];

export const individual3=[{piece1:{quant:4,sides:6,type:"Peças de Prata",multiply:100},piece2:{quant:1,sides:6,type:"Peças de Ouro",multiply:100}},{piece1:{quant:1,sides:6,type:"Peças de Electrum",multiply:100},piece2:{quant:1,sides:6,type:"Peças de Ouro",multiply:100}},{piece1:{quant:2,sides:6,type:"Peças de Ouro",multiply:100},piece2:{quant:1,sides:6,type:"Peças de Platina",multiply:10}},{piece1:{quant:2,sides:6,type:"Peças de Ouro",multiply:100},piece2:{quant:2,sides:6,type:"Peças de Platina",multiply:10}}];

export const individual4=[{piece1:{quant:2,sides:6,type:"Peças de Electrum",multiply:1e3},piece2:{quant:8,sides:6,type:"Peças de Ouro",multiply:100}},{piece1:{quant:1,sides:6,type:"Peças de Ouro",multiply:1e3},piece2:{quant:1,sides:6,type:"Peças de Platina",multiply:100}},{piece1:{quant:1,sides:6,type:"Peças de Ouro",multiply:1e3},piece2:{quant:2,sides:6,type:"Peças de Platina",multiply:100}}];


export const hoard1=[{gemArt:{quant:2,sides:6,type:"Gemas",table:"10GP"}},{gemArt:{quant:2,sides:4,type:"Objetos de Arte",table:"25GP"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"50GP"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"10GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableA"}},{gemArt:{quant:2,sides:4,type:"Objetos de Arte",table:"25GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableA"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"50GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableA"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"10GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableB"}},{gemArt:{quant:2,sides:4,type:"Objetos de Arte",table:"25GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableB"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"50GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableB"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"10GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableC"}},{gemArt:{quant:2,sides:4,type:"Objetos de Arte",table:"25GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableC"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"50GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableC"}},{gemArt:{quant:2,sides:4,type:"Objetos de Arte",table:"25GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableF"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"50GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableF"}},{gemArt:{quant:2,sides:4,type:"Objetos de Arte",table:"25GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableG"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"50GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableG"}}];
export const hoard2=[{gemArt:{quant:2,sides:4,table:"25GP",type:"Objetos de Arte"}},{gemArt:{quant:3,sides:6,table:"50GP",type:"Gemas"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"}},{gemArt:{quant:2,sides:4,table:"25GP",type:"Objetos de Arte"}},{gemArt:{quant:2,sides:4,table:"25GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableA"}},{gemArt:{quant:3,sides:6,table:"50GP",type:"Gemas"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableA"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableA"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableA"}},{gemArt:{quant:2,sides:4,table:"25GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableB"}},{gemArt:{quant:3,sides:6,table:"50GP",type:"Gemas"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableB"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableB"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableB"}},{gemArt:{quant:2,sides:4,table:"25GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableC"}},{gemArt:{quant:3,sides:6,table:"50GP",type:"Gemas"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableC"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableC"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableC"}},{gemArt:{quant:2,sides:4,table:"25GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,type:"Itens Mágicos",table:"TableD"}},{gemArt:{quant:3,sides:6,table:"50GP",type:"Gemas"},magItemA:{quant:1,sides:1,type:"Itens Mágicos",table:"TableD"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"},magItemA:{quant:1,sides:1,type:"Itens Mágicos",table:"TableD"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,type:"Itens Mágicos",table:"TableD"}},{gemArt:{quant:2,sides:4,table:"25GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableF"}},{gemArt:{quant:3,sides:6,table:"50GP",type:"Gemas"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableF"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableF"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableF"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableG"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableG"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"},magItemA:{quant:1,sides:1,type:"Itens Mágicos",table:"TableH"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,type:"Itens Mágicos",table:"TableH"}}];
export const hoard3=[{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"}},{gemArt:{quant:2,sides:4,table:"750GP",type:"Objetos de Arte"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableA",type:"Itens Mágicos"},magItemB:{quant:1,sides:6,table:"TableB",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"750GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableA",type:"Itens Mágicos"},magItemB:{quant:1,sides:6,table:"TableB",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableA",type:"Itens Mágicos"},magItemB:{quant:1,sides:6,table:"TableB",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableA",type:"Itens Mágicos"},magItemB:{quant:1,sides:6,table:"TableB",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"750GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"},magItemA:{quant:1,sides:6,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:6,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"750GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"750GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"},magItemA:{quant:1,sides:1,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:1,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,table:"TableF",type:"Itens Mágicos"},magItemB:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"750GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,table:"TableF",type:"Itens Mágicos"},magItemB:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"},magItemA:{quant:1,sides:1,table:"TableF",type:"Itens Mágicos"},magItemB:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:1,table:"TableF",type:"Itens Mágicos"},magItemB:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"750GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,table:"TableI",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"},magItemA:{quant:1,sides:1,table:"TableI",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:1,table:"TableI",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:1,table:"TableI",type:"Itens Mágicos"}}];
export const hoard4=[{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:8,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:10,table:"2500GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:8,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:4,table:"7500GP",type:"Objetos de Arte "},magItemA:{quant:1,sides:8,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:8,table:"5000GP",type:"Gemas"},magItemA:{quant:1,sides:8,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:6,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:10,table:"2500GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:4,table:"7500GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:8,table:"5000GP",type:"Gemas"},magItemA:{quant:1,sides:6,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:6,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:10,table:"2500GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:4,table:"7500GP",type:"Objetos de Arte "},magItemA:{quant:1,sides:6,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:8,table:"5000GP",type:"Gemas"},magItemA:{quant:1,sides:6,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"gem"},magItemA:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:10,table:"2500GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:4,table:"7500GP",type:"Objetos de Arte "},magItemA:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:8,table:"5000GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"gem"},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:10,table:"2500GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:4,table:"7500GP",type:"Objetos de Arte "},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:8,table:"5000GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableI",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:10,table:"2500GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableI",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:4,table:"7500GP",type:"Objetos de Arte "},magItemA:{quant:1,sides:1,table:"TableF",type:"Itens Mágicos"},magItemB:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:8,table:"5000GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableI",type:"Itens Mágicos"}}];
export const gem10=["Azurita","Ágata malhada ","Quartzo azul","Ágata ocular","Hematita","Lápis lazúli","Malaquita","Ágata musgo","Obsidiana","Rodocrosita","Olho de tigre","Turquesa"]
export const gem50=["Pedra de sangue","Cornalina","Calcedônia","Crisoprásio","Citrina","Jaspe","Pedra lunar","Ônix","Quartzo","Sardônica","Quartzo rosa estrela","Zircônio",]
export const gem100=["Âmbar","Ametista","Crisoberilo","Coral","Granada","Jade","Jato","Pérola","Espinela","Turmalina"]
export const gem500=["Alexandrita","Água-marinha","Pérola negra","Espinela azul","Peridoto","Topázio"]
export const gem1000=["Opala negra","Safira azul","Esmeralda","Opala de fogo","Opala","Rubi estrela","Safira estrela","Safira amarela"]
export const gem5000=["Safira negra","Diamante","Jacinto","Rubi"]
export const art25=["Jarro de prata","Estatueta esculpida em osso","Bracelete de ouro pequeno","Vestimenta de tecido dourado","Máscara de veludo negra costurada com fios de prata","Cálice de cobre com filigrana prateada","Par de dados de osso com gravuras","Pequeno espelho numa moldura de madeira pintada","Lenço de seda bordado","Broche de ouro com um retrato pintado dentro"]
export const art250=["Anel de ouro cravejado com pedras de sangue","Estatueta esculpida em marfim","Bracelete de ouro largo","Gargantilha de prata com um pingente de pedra preciosa","Coroa de bronze","Robe de seda com adornos de ouro","Grande tapeçaria elegante","Caneca de bronze com jades incrustadas","Caixa de miniaturas de animais em turquesa","Gaiola de pássaro de ouro com filigrana de electro"]
export const art750=["Cálice de prata cravejado com pedras da lua","Espada longa de lâmina prateada com conjunto de jatos no cabo","Harpa de madeira exótica com marfim incrustado e gemas de zircónio","Pequeno ídolo de ouro","Pente de ouro em formato de dragão cravejada com granadas vermelhas nos olhos","Rolha de garrafa gravada com folhas de ouro e cravejada com ametistas","Adaga de electro cerimonial com uma pérola negra no pomo","Broche de prata e ouro","Estatueta de obsidiana com detalhes e incrustações de ouro","Máscara de guerra de ouro pintada"]
export const art2500=["Corrente de ouro elegante cravejada com uma opala de fogo","Antiga pintura obra-prima","Manto de seda e veludo bordado com diversas pedras da lua cravejadas","Bracelete de platina cravejado com uma safira","Luvas bordadas com lascas de joias","Peúga cheia de joias","Caixa de música de ouro","Argola de ouro cravejada com quatro águasmarinhas","Tapa-olho com um olho falso cravejado em uma safira azul e uma pedra da lua","Um colar de pequenas pérolas rosas"]
export const art7500=["Coroa de ouro cheia de joias","Anel de platina cheio de joias","Pequena estatueta de ouro cravejada com rubis","Taça de ouro cravejada com esmeraldas","Caixa de joias de ouro com filigrana de platina","Sarcófago infantil de ouro pintado","Jogo de tabuleiro de jade com peças de ouro maciço","Chifre de marfim adornado com filigrana de ouro"]

export const tableA=[
    {value:"50GP",name:"Poção de cura",page:153},
    {value:"50GP",name:"Pergaminho de magia (truque)",page:197},
    {value:"50GP",name:"Poção de escalar",page:202},
    {value:"100",name:"Pergaminho de magia (1° nível)",page:197},
    {value:"250",name:"Pergaminho de magia (2° nível)",page:197},
    {value:"250GP",name:"Poção de cura maior",page:201},
    {value:"3000GP",name:"Mochila de carga",page:194},
    {value:"4000GP",name:"Globo de fluxo",page:187}
]
export const tableB=[
    {value:"250GP",name:"Poção de cura maior",page:201},
    {value:"500GP",name:"Poção de sopro de fogo",page:203},
    {value:"400GP",name:"Poção de resistência",page:203},
    {value:"250GP",name:"Munição +1",page:194},
    {value:"300GP",name:"Poção de amizade animal",page:201},
    {value:"50GP",name:"Poção de força do gigante da colina",page:202},
    {value:"50GP",name:"Poção de aumentar",page:201},
    {value:"50GP",name:"Poção de respirar na água",page:203},
    {value:"50GP",name:"Pergaminho de magia (2° nível)",page:197},
    {value:"50GP",name:"Pergaminho de magia (3° nível)",page:197},
    {value:"50GP",name:"Mochila de carga",page:194},
    {value:"50GP",name:"Unguento de Keoghtom",page:210},
    {value:"50GP",name:"Óleo escorregadio",page:195},
    {value:"50GP",name:"Pó do desaparecimento",page:201},
    {value:"50GP",name:"Pó da seca",page:201},
    {value:"50GP",name:"Pó de espirrar e tossir",page:200},
    {value:"50GP",name:"Gema elemental",page:186},
    {value:"50GP",name:"Filtro do amor",page:183},
    {value:"50GP",name:"Jarro de alquimia",page:187},
    {value:"50GP",name:"Capa de respirar na água",page:171},
    {value:"50GP",name:"Manto da arraia",page:191},
    {value:"50GP",name:"Globo de fluxo",page:187},
    {value:"50GP",name:"Óculos noturnos",page:203},
    {value:"50GP",name:"Elmo de compreensão de idiomas",page:177},
    {value:"50GP",name:"Bastão imóvel",page:163},
    {value:"50GP",name:"Lanterna de revelação",page:189},
    {value:"50GP",name:"Armadura do marinheiro",page:156},
    {value:"50GP",name:"Armadura de mitral",page:156},
    {value:"50GP",name:"Poção de envenenamento",page:202},
    {value:"50GP",name:"Anel de natação",page:153},
    {value:"50GP",name:"Robe dos itens úteis",page:205},
    {value:"50GP",name:"Corda de escalada",page:174},
    {value:"50GP",name:"Sela do cavaleiro",page:207},
    {value:"50GP",name:"Varinha de detectar magia",page:212},
    {value:"50GP",name:"Varinha de segredos",page:213},
]
export const tableC=[
    {value:"250GP",name:"Poção de cura maior",page:153},
    {value:"50GP",name:"Pergaminho de magia (4° nível)",page:197},
    {value:"50GP",name:"Munição +2",page:194},
    {value:"50GP",name:"Poção de clarividência",page:201},
    {value:"50GP",name:"Poção de encolher",page:201},
    {value:"50GP",name:"Poção de forma gasosa",page:202},
    {value:"50GP",name:"Poção de força do gigante do gelo",page:202},
    {value:"50GP",name:"Poção de força do gigante de pedra",page:202},
    {value:"50GP",name:"Poção de heroísmo",page:202},
    {value:"50GP",name:"Poção de invulnerabilidade",page:203},
    {value:"50GP",name:"Poção de ler mentes",page:203},
    {value:"50GP",name:"Pergaminho de magia (5° nível)",page:197},
    {value:"50GP",name:"Elixir de saúde",page:177},
    {value:"50GP",name:"Óleo de forma etérea",page:194},
    {value:"50GP",name:"Poção de força do gigante do fogo",page:202},
    {value:"50GP",name:"Pena de Quaal",page:196},
    {value:"50GP",name:"Pergaminho de proteção",page:199},
    {value:"50GP",name:"Saco de feijões",page:206},
    {value:"50GP",name:"Contas de força",page:173},
    {value:"50GP",name:"Carrilhão de abertura",page:172},
    {value:"50GP",name:"Decantador de água infinita",page:175},
    {value:"50GP",name:"Olhos de visão momentânea",page:204},
    {value:"50GP",name:"Barco dobrável",page:160},
    {value:"50GP",name:"Sacola prestativa de Heward",page:206},
    {value:"50GP",name:"Ferraduras da velocidade",page:183},
    {value:"50GP",name:"Colar de bolas de fogo",page:173},
    {value:"50GP",name:"Periapto de saúde",page:200},
    {value:"50GP",name:"Pedras de mensagem",page:196}
]
export const tableD=[
    {value:"50GP",name:"Poção de cura suprema",page:153},
    {value:"50GP",name:"Poção de invisibilidade",page:202},
    {value:"50GP",name:"Poção de velocidade",page:203},
    {value:"50GP",name:"Pergaminho de magia (6° nível)",page:197},
    {value:"50GP",name:"Pergaminho de magia (7° nível)",page:197},
    {value:"50GP",name:"Munição +3",page:194},
    {value:"50GP",name:"Óleo de precisão",page:203},
    {value:"50GP",name:"Poção de voo",page:203},
    {value:"50GP",name:"Poção de força do gigante das nuvens",page:202},
    {value:"50GP",name:"Poção de longevidade",page:203},
    {value:"50GP",name:"Poção de vitalidade",page:203},
    {value:"50GP",name:"Pergaminho de magia (8° nível)",page:197},
    {value:"50GP",name:"Ferraduras de zéfiro",page:183},
    {value:"50GP",name:"Pigmentos maravilhosos de Nolzur",page:200},
    {value:"50GP",name:"Bolsa devoradora",page:164},
    {value:"50GP",name:"Buraco portátil",page:165}
]
export const tableE=[
    {value:"50GP",name:"Pergaminho de magia (8° nível)",page:197},
    {value:"50GP",name:"Poção de força do gigante da tempestade",page:202},
    {value:"50GP",name:"Poção de cura suprema",page:153},
    {value:"50GP",name:"Pergaminho de magia (9° nível)",page:197},
    {value:"50GP",name:"Solvente universal",page:207},
    {value:"50GP",name:"Flecha assassina",page:184},
    {value:"50GP",name:"Cola soberana",page:173}
]
export const tableF=[
    {value:"50GP",name:"Arma +1",page:155},
    {value:"50GP",name:"Escudo +1",page:178},
    {value:"50GP",name:"Escudo sentinela",page:178},
    {value:"50GP",name:"Amuleto de proteção contra detecção e localização",page:150},
    {value:"50GP",name:"Botas élficas",page:165},
    {value:"50GP",name:"Botas de caminhar e saltar",page:164},
    {value:"50GP",name:"Braçadeiras de arquearia",page:165},
    {value:"50GP",name:"Broche do escudo",page:165},
    {value:"50GP",name:"Vassoura voadora",page:214},
    {value:"50GP",name:"Manto élfico",page:192},
    {value:"50GP",name:"Manto de proteção",page:192},
    {value:"50GP",name:"Manoplas de força do ogro",page:191},
    {value:"50GP",name:"Chapéu de disfarce",page:172},
    {value:"50GP",name:"Azagaia de relâmpago",page:157},
    {value:"50GP",name:"Pérola do poder",page:200},
    {value:"50GP",name:"Bastão guardião de pactos +1",page:163},
    {value:"50GP",name:"Sandálias de patas de aranha",page:207},
    {value:"50GP",name:"Cajado da víbora",page:166},
    {value:"50GP",name:"Cajado da píton",page:166},
    {value:"50GP",name:"Espada da vingança",page:180},
    {value:"50GP",name:"Tridente de comandar peixes",page:209},
    {value:"50GP",name:"Varinha de misseis mágicos",page:212},
    {value:"50GP",name:"Varinha do arcano de guerra +1",page:214},
    {value:"50GP",name:"Varinha de teia",page:213},
    {value:"50GP",name:"Arma de alerta",page:155},
    {value:"50GP",name:"Armadura de adamante (cota de malha)",page:155},
    {value:"50GP",name:"Armadura de adamante (camisão de malha)",page:155},
    {value:"50GP",name:"Armadura de adamante (brunea)",page:155},
    {value:"50GP",name:"Bolsa de truques (cinza)",page:163},
    {value:"50GP",name:"Bolsa de truques (ferrugem)",page:163},
    {value:"50GP",name:"Bolsa de truques (bronze)",page:163},
    {value:"2500",name:"Botas do inverno",page:164},
    {value:"50GP",name:"Diadema da destruição",page:175},
    {value:"50GP",name:"Baralho das ilusões",page:157},
    {value:"50GP",name:"Garrafa da fumaça eterna",page:185},
    {value:"50GP",name:"Olhos do encantamento",page:204},
    {value:"50GP",name:"Olhos de águia",page:203},
    {value:"50GP",name:"Estátua de poderes incríveis (corvo de prata)",page:181},
    {value:"50GP",name:"Gema da luminosidade",page:186},
    {value:"50GP",name:"Luvas de apanhar projeteis",page:189},
    {value:"50GP",name:"Luvas de nadar e escalar",page:189},
    {value:"50GP",name:"Luvas do ladrão",page:189},
    {value:"50GP",name:"Tiara do intelecto",page:208},
    {value:"50GP",name:"Elmo de telepatia",page:177},
    {value:"50GP",name:"Instrumento dos bardos (alaúde de Doss)",page:187},
    {value:"50GP",name:"Instrumento dos bardos (bandolim de Fochlucan)",page:187},
    {value:"50GP",name:"Instrumento dos bardos (citara de Mac-Fuimidh)",page:187},
    {value:"50GP",name:"Medalhão de pensamentos",page:194},
    {value:"50GP",name:"Colar de adaptação",page:173},
    {value:"50GP",name:"Periapto da cicatrização",page:199},
    {value:"50GP",name:"Flauta assombrada",page:183},
    {value:"50GP",name:"Flauta dos esgotos",page:184},
    {value:"50GP",name:"Anel de saltar",page:154},
    {value:"50GP",name:"Anel de escudo mental",page:152},
    {value:"50GP",name:"Anel de calor",page:151},
    {value:"50GP",name:"Anel de andar na água",page:151},
    {value:"50GP",name:"Aljava de Ehlonna",page:150},
    {value:"50GP",name:"Pedra da boa sorte",page:195},
    {value:"50GP",name:"Leque do vento",page:189},
    {value:"50GP",name:"Botas aladas",page:164}
]
export const tableG=[
    {value:"50GP",name:"Arma +2",page:155},
    {value:"50GP",name:"Estátua de poderes incríveis",page:181},
    {value:"50GP",name:"Armadura de adamante (peitoral)",page:155},
    {value:"50GP",name:"Armadura de adamante (cota de talas)",page:155},
    {value:"50GP",name:"Amuleto de saúde",page:150},
    {value:"50GP",name:"Armadura de vulnerabilidade",page:156},
    {value:"50GP",name:"Escudo apanhador de flechas",page:178},
    {value:"50GP",name:"Cinto dos anões",page:172},
    {value:"50GP",name:"Cinturão de força do gigante da colina",page:172},
    {value:"50GP",name:"Machado furioso",page:190},
    {value:"50GP",name:"Botas de levitação",page:164},
    {value:"50GP",name:"Botas de velocidade",page:164},
    {value:"50GP",name:"Bacia de comandar elementais da água",page:157},
    {value:"50GP",name:"Braceletes de defesa",page:165},
    {value:"50GP",name:"Braseiro de comandar elementais do fogo",page:165},
    {value:"50GP",name:"Capa do saltimbanco",page:172},
    {value:"50GP",name:"Incensório de comandar elementais do ar",page:0},
    {value:"50GP",name:"Cota de malha +1",page:0},
    {value:"50GP",name:"Armadura da resistência (cota de malha)",page:0},
    {value:"50GP",name:"Camisão de malha +1",page:0},
    {value:"50GP",name:"Armadura da resistência (camisão de malha)",page:0},
    {value:"50GP",name:"Manto de deslocamento",page:191},
    {value:"50GP",name:"Manto do morcego",page:192},
    {value:"50GP",name:"Cubo de força",page:175},
    {value:"50GP",name:"Fortaleza instantânea de Daern",page:184},
    {value:"50GP",name:"Adaga de envenenamento",page:150},
    {value:"50GP",name:"Algemas dimensionais",page:150},
    {value:"50GP",name:"Matadora de dragões",page:193},
    {value:"50GP",name:"Malha élfica",page:191},
    {value:"50GP",name:"Língua flamejante",page:189},
    {value:"50GP",name:"Gema de visão",page:186},
    {value:"50GP",name:"Matador de gigantes",page:194},
    {value:"50GP",name:"Couro batido encantador",page:175},
    {value:"50GP",name:"Elmo de teletransporte",page:177},
    {value:"50GP",name:"Trombeta da destruição",page:209},
    {value:"50GP",name:"Trombeta do Valhalla (prata e latão)",page:209},
    {value:"50GP",name:"Instrumento dos bardos (mandolim de Canaith)",page:187},
    {value:"50GP",name:"Instrumento dos bardos (lira de Cli)",page:187},
    {value:"50GP",name:"Pedra iônica (prontidão)",page:195},
    {value:"50GP",name:"Pedra iônica (proteção)",page:195},
    {value:"50GP",name:"Pedra iônica (armazenamento)",page:195},
    {value:"50GP",name:"Pedra iônica (sustento)",page:195},
    {value:"50GP",name:"Faixas de ferro de Bilarro",page:183},
    {value:"50GP",name:"Armadura de couro +1",page:0},
    {value:"50GP",name:"Armadura de resistência (couro)",page:156},
    {value:"50GP",name:"Maça do rompimento",page:190},
    {value:"50GP",name:"Maça de destruição",page:189},
    {value:"50GP",name:"Maça do terror",page:190},
    {value:"50GP",name:"Manto de resistência à magia",page:192},
    {value:"50GP",name:"Corrente de contas de oração",page:174},
    {value:"50GP",name:"Periapto de proteção contra veneno",page:199},
    {value:"50GP",name:"Anel de cativar animais",page:151},
    {value:"50GP",name:"Anel de evasão",page:153},
    {value:"50GP",name:"Anel de queda suave",page:153},
    {value:"50GP",name:"Anel de ação livre",page:151},
    {value:"50GP",name:"Anel de proteção",page:153},
    {value:"50GP",name:"Anel de resistência",page:154},
    {value:"50GP",name:"Anel de armazenar magia",page:151},
    {value:"50GP",name:"Anel do aríete",page:154},
    {value:"50GP",name:"Anel de visão de raio-X",page:154},
    {value:"50GP",name:"Robe dos olhos",page:206},
    {value:"50GP",name:"Bastão da obediência",page:0},
    {value:"50GP",name:"Bastão guardião de pactos +2",page:163},
    {value:"50GP",name:"Corda de estrangulamento",page:174},
    {value:"50GP",name:"Brunea +1",page:0},
    {value:"50GP",name:"Armadura de resistência (brunea)",page:156},
    {value:"50GP",name:"Escudo +2",page:178},
    {value:"50GP",name:"Escudo de atração de projeteis",page:178},
    {value:"50GP",name:"Cajado de enfeitiçar",page:168},
    {value:"50GP",name:"Cajado de cura",page:168},
    {value:"50GP",name:"Cajado de enxame de insetos",page:169},
    {value:"50GP",name:"Cajado das florestas",page:166},
    {value:"50GP",name:"Cajado do definhamento",page:168},
    {value:"50GP",name:"Pedra de comandar elementais da terra",page:195},
    {value:"50GP",name:"Lâmina do sol",page:188},
    {value:"50GP",name:"Espada do furto de vidas",page:180},
    {value:"50GP",name:"Espada do sangramento",page:180},
    {value:"50GP",name:"Bastão do tentáculo",page:163},
    {value:"50GP",name:"Arma viciosa",page:155},
    {value:"50GP",name:"Varinha de obrigação",page:213},
    {value:"50GP",name:"Varinha de detecção de inimigos",page:210},
    {value:"50GP",name:"Varinha de medo",page:212},
    {value:"50GP",name:"Varinha de bolas de fogo",page:210},
    {value:"50GP",name:"Varinhas de relâmpagos",page:213},
    {value:"50GP",name:"Varinha de paralisia",page:213},
    {value:"50GP",name:"Varinha do arcano de guerra +2",page:214},
    {value:"50GP",name:"Varinha das maravilhas",page:210},
    {value:"50GP",name:"Asas voadoras",page:157}
]
export const tableH=[
    {value:"50GP",name:"Arma +3",page:155},
    {value:"50GP",name:"Amuleto dos planos",page:150},
    {value:"50GP",name:"Tapete voador",page:208},
    {value:"50GP",name:"Bola de cristal (versão muito rara)",page:163},
    {value:"50GP",name:"Anel de regeneração",page:154},
    {value:"50GP",name:"Anel de estrelas cadentes",page:152},
    {value:"50GP",name:"Anel de telecinésia",page:154},
    {value:"50GP",name:"Robe das cores cintilantes",page:204},
    {value:"50GP",name:"Robe das estrelas",page:204},
    {value:"50GP",name:"Bastão de absorção",page:161},
    {value:"50GP",name:"Bastão de prontidão",page:161},
    {value:"50GP",name:"Bastão de segurança",page:162},
    {value:"50GP",name:"Bastão guardião de pactos +3",page:163},
    {value:"50GP",name:"Cimitarra da velocidade",page:172},
    {value:"50GP",name:"Escudo +3",page:178},
    {value:"50GP",name:"Cajado do fogo",page:169},
    {value:"50GP",name:"Cajado do frio",page:170},
    {value:"50GP",name:"Cajado do poder",page:170},
    {value:"50GP",name:"Cajado de ataque",page:168},
    {value:"50GP",name:"Cajado de trovão e relâmpago",page:169},
    {value:"50GP",name:"Espada decepadora",page:180},
    {value:"50GP",name:"Varinha de metamorfose",page:212},
    {value:"50GP",name:"Varinha do arcano de guerra +3",page:214},
    {value:"50GP",name:"Armadura de adamante (meia-armadura)",page:155},
    {value:"50GP",name:"Armadura de adamante (placas)",page:155},
    {value:"50GP",name:"Escudo animado",page:178},
    {value:"50GP",name:"Cinturão de força do gigante do fogo",page:172},
    {value:"50GP",name:"Cinturão de força do gigante do frio (ou de pedra)",page:172},
    {value:"50GP",name:"Peitoral +1",page:0},
    {value:"50GP",name:"Armadura de resistência (peitoral)",page:156},
    {value:"50GP",name:"Vela da invocação",page:214},
    {value:"50GP",name:"Cota de malha +2",page:0},
    {value:"50GP",name:"Camisão de malha +2",page:0},
    {value:"50GP",name:"Manto da aranha",page:191},
    {value:"50GP",name:"Espada dançarina",page:179},
    {value:"50GP",name:"Armadura demoníaca",page:156},
    {value:"50GP",name:"Brunea de escamas de dragão",page:165},
    {value:"50GP",name:"Armadura anã",page:155},
    {value:"50GP",name:"Arremessador anão",page:156},
    {value:"50GP",name:"Garrafa do efreeti",page:186},
    {value:"50GP",name:"Estátua de poderes incríveis (corcel de obsidiana)",page:181},
    {value:"50GP",name:"Marca congelante",page:193},
    {value:"50GP",name:"Elmo brilhante",page:177},
    {value:"50GP",name:"Trombeta do Valhalla (bronze)",page:209},
    {value:"50GP",name:"Instrumento dos bardos (harpa de Anstruth)",page:187},
    {value:"50GP",name:"Pedra iônica (absorção)",page:195 },
    {value:"50GP",name:"Pedra iônica (agilidade)",page:195 },
    {value:"50GP",name:"Pedra iônica (fortitude)",page:195 },
    {value:"50GP",name:"Pedra iônica (intuição)",page:195 },
    {value:"50GP",name:"Pedra iônica (intelecto)",page:195 },
    {value:"50GP",name:"Pedra iônica (liderança)",page:195 },
    {value:"50GP",name:"Pedra iônica (força)",page:195 },
    {value:"50GP",name:"Armadura de couro +2",page:0},
    {value:"50GP",name:"Manual da saúde corporal",page:192},
    {value:"50GP",name:"Manual do bom exercício",page:192},
    {value:"50GP",name:"Manual dos golens",page:192},
    {value:"50GP",name:"Manual da rapidez de movimentos",page:192},
    {value:"50GP",name:"Espelho do aprisionamento",page:181},
    {value:"50GP",name:"Ladra das nove vidas",page:188},
    {value:"50GP",name:"Arco do juramento",page:154},
    {value:"50GP",name:"Brunea +2",page:0},
    {value:"50GP",name:"Escudo de proteção contra magia",page:178},
    {value:"50GP",name:"Cota de talas +1",page:0},
    {value:"50GP",name:"Armadura de resistência (cota de talas)",page:156},
    {value:"50GP",name:"Armadura de couro batido +1",page:0},
    {value:"50GP",name:"Armadura de resistência (couro batido)",page:156},
    {value:"50GP",name:"Tomo dos grandes pensamentos",page:209},
    {value:"50GP",name:"Tomo de liderança e influência",page:209},
    {value:"50GP",name:"Tomo da compreensão",page:208}
]
export const tableI=[
    {value:"50GP",name:"Defensora",page:666},
{value:"50GP",name:"Martelo dos trovões",page:666},
{value:"50GP",name:"Lâmina da sorte",page:666},
{value:"50GP",name:"Espada de retaliação",page:666},
{value:"50GP",name:"Vingadora sagrada",page:666},
{value:"50GP",name:"Anel de invocação de djinni",page:666},
{value:"50GP",name:"Anel de invisibilidade",page:666},
{value:"50GP",name:"Anel de refletir magias",page:666},
{value:"50GP",name:"Bastão do grande poder",page:666},
{value:"50GP",name:"Cajado do arcano",page:666},
{value:"50GP",name:"Espada vorpal",page:666},
{value:"50GP",name:"Cinturão de força do gigante das nuvens",page:666},
{value:"50GP",name:"Peitoral +2",page:666},
{value:"50GP",name:"Cota de malha +3",page:666},
{value:"50GP",name:"Camisão de malha +3",page:666},
{value:"50GP",name:"Manto de invisibilidade",page:666},
{value:"50GP",name:"Bola de cristal (versão lendária)",page:163},
{value:"50GP",name:"Meia-armadura +1",page:666},
{value:"50GP",name:"Frasco de ferro",page:666},
{value:"50GP",name:"Armadura de couro +3",page:666},
{value:"50GP",name:"Armadura de placas +1",page:666},
{value:"50GP",name:"Robe do arquimago",page:666},
{value:"50GP",name:"Bastão de ressurreição",page:666},
{value:"50GP",name:"Brunea +1",page:666},
{value:"50GP",name:"Escaravelho da proteção",page:666},
{value:"50GP",name:"Cota de talas +2",page:666},
{value:"50GP",name:"Armadura de couro batido +2",page:666},
{value:"50GP",name:"Poço dos muitos mundos",page:666},
{value:"50GP",name:"Armadura mágica",page:666},
{value:"50GP",name:"Dispositivo de Kwalish",page:666},
{value:"50GP",name:"Armadura de invulnerabilidade",page:666},
{value:"50GP",name:"Cinturão de força do gigante da tempestade",page:666},
{value:"50GP",name:"Cubo do portal",page:666},
{value:"50GP",name:"Baralho das surpresas",page:157},
{value:"50GP",name:"Malha do efreeti",page:666},
{value:"50GP",name:"Armadura de resistência (meia-armadura)",page:156},
{value:"50GP",name:"Trombeta do Valhalla (ferro)",page:666},
{value:"50GP",name:"Instrumento dos bardos (harpa de Ollamh)",page:666},
{value:"50GP",name:"Pedra iônica (absorção maior)",page:666},
{value:"50GP",name:"Pedra iônica (maestria)",page:666},
{value:"50GP",name:"Pedra iônica (regeneração)",page:666},
{value:"50GP",name:"Armadura de placas da forma etérea",page:666},
{value:"50GP",name:"Armadura de placas da resistência",page:666},
{value:"50GP",name:"Anel de comandar elementais do ar",page:666},
{value:"50GP",name:"Anel de comandar elementais da terra",page:666},
{value:"50GP",name:"Anel de comandar elementais do fogo",page:666},
{value:"50GP",name:"Anel dos três desejos",page:666},
{value:"50GP",name:"Anel de comandar elementais da água",page:666},
{value:"50GP",name:"Esfera da aniquilação",page:666},
{value:"50GP",name:"Talismã da bondade pura",page:666},
{value:"50GP",name:"Talismã da esfera",page:666},
{value:"50GP",name:"Talismã do mal absoluto",page:666},
{value:"50GP",name:"Tomo da língua quieta",page:666}
]
