

export const individual1=[{piece1:{quant:5,sides:6,type:"Peças de Cobre",multiply:1}},{piece1:{quant:4,sides:6,type:"Peças de Prata",multiply:1}},{piece1:{quant:3,sides:6,type:"Peças de Electrum",multiply:1}},{piece1:{quant:3,sides:6,type:"Peças de Ouro",multiply:1}},{piece1:{quant:1,sides:6,type:"Peças de Platina",multiply:1}}];

export const individual2=[{piece1:{quant:4,sides:6,type:"Peças de Cobre",multiply:100},piece2:{quant:1,sides:6,type:"Peças de Electrum",multiply:10}},{piece1:{quant:6,sides:6,type:"Peças de Prata",multiply:10},piece2:{quant:2,sides:6,type:"Peças de Ouro",multiply:10}},{piece1:{quant:1,sides:6,type:"Peças de Electrum",multiply:100},piece2:{quant:2,sides:6,type:"Peças de Ouro",multiply:10}},{piece1:{quant:4,sides:6,type:"Peças de Ouro",multiply:10}},{piece1:{quant:2,sides:6,type:"Peças de Ouro",multiply:10},piece2:{quant:3,sides:6,type:"Peças de Platina",multiply:1}}];

export const individual3=[{piece1:{quant:4,sides:6,type:"Peças de Prata",multiply:100},piece2:{quant:1,sides:6,type:"Peças de Ouro",multiply:100}},{piece1:{quant:1,sides:6,type:"Peças de Electrum",multiply:100},piece2:{quant:1,sides:6,type:"Peças de Ouro",multiply:100}},{piece1:{quant:2,sides:6,type:"Peças de Ouro",multiply:100},piece2:{quant:1,sides:6,type:"Peças de Platina",multiply:10}},{piece1:{quant:2,sides:6,type:"Peças de Ouro",multiply:100},piece2:{quant:2,sides:6,type:"Peças de Platina",multiply:10}}];

export const individual4=[{piece1:{quant:2,sides:6,type:"Peças de Electrum",multiply:1e3},piece2:{quant:8,sides:6,type:"Peças de Ouro",multiply:100}},{piece1:{quant:1,sides:6,type:"Peças de Ouro",multiply:1e3},piece2:{quant:1,sides:6,type:"Peças de Platina",multiply:100}},{piece1:{quant:1,sides:6,type:"Peças de Ouro",multiply:1e3},piece2:{quant:2,sides:6,type:"Peças de Platina",multiply:100}}];


export const hoard1=[{gemArt:{quant:2,sides:6,type:"Gemas",table:"10GP"}},{gemArt:{quant:2,sides:4,type:"Objetos de Arte",table:"25GP"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"50GP"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"10GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableA"}},{gemArt:{quant:2,sides:4,type:"Objetos de Arte",table:"25GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableA"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"50GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableA"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"10GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableB"}},{gemArt:{quant:2,sides:4,type:"Objetos de Arte",table:"25GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableB"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"50GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableB"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"10GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableC"}},{gemArt:{quant:2,sides:4,type:"Objetos de Arte",table:"25GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableC"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"50GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableC"}},{gemArt:{quant:2,sides:4,type:"Objetos de Arte",table:"25GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableF"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"50GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableF"}},{gemArt:{quant:2,sides:4,type:"Objetos de Arte",table:"25GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableG"}},{gemArt:{quant:2,sides:6,type:"Gemas",table:"50GP"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableG"}}];
export const hoard2=[{gemArt:{quant:2,sides:4,table:"25GP",type:"Objetos de Arte"}},{gemArt:{quant:3,sides:6,table:"50GP",type:"Gemas"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"}},{gemArt:{quant:2,sides:4,table:"25GP",type:"Objetos de Arte"}},{gemArt:{quant:2,sides:4,table:"25GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableA"}},{gemArt:{quant:3,sides:6,table:"50GP",type:"Gemas"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableA"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableA"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableA"}},{gemArt:{quant:2,sides:4,table:"25GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableB"}},{gemArt:{quant:3,sides:6,table:"50GP",type:"Gemas"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableB"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableB"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableB"}},{gemArt:{quant:2,sides:4,table:"25GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableC"}},{gemArt:{quant:3,sides:6,table:"50GP",type:"Gemas"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableC"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableC"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableC"}},{gemArt:{quant:2,sides:4,table:"25GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,type:"Itens Mágicos",table:"TableD"}},{gemArt:{quant:3,sides:6,table:"50GP",type:"Gemas"},magItemA:{quant:1,sides:1,type:"Itens Mágicos",table:"TableD"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"},magItemA:{quant:1,sides:1,type:"Itens Mágicos",table:"TableD"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,type:"Itens Mágicos",table:"TableD"}},{gemArt:{quant:2,sides:4,table:"25GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableF"}},{gemArt:{quant:3,sides:6,table:"50GP",type:"Gemas"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableF"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableF"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableF"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"},magItemA:{quant:1,sides:4,type:"Itens Mágicos",table:"TableG"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,type:"Itens Mágicos",table:"TableG"}},{gemArt:{quant:3,sides:6,table:"100GP",type:"Gemas"},magItemA:{quant:1,sides:1,type:"Itens Mágicos",table:"TableH"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,type:"Itens Mágicos",table:"TableH"}}];
export const hoard3=[{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"}},{gemArt:{quant:2,sides:4,table:"750GP",type:"Objetos de Arte"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableA",type:"Itens Mágicos"},magItemB:{quant:1,sides:6,table:"TableB",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"750GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableA",type:"Itens Mágicos"},magItemB:{quant:1,sides:6,table:"TableB",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableA",type:"Itens Mágicos"},magItemB:{quant:1,sides:6,table:"TableB",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableA",type:"Itens Mágicos"},magItemB:{quant:1,sides:6,table:"TableB",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"750GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"},magItemA:{quant:1,sides:6,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:6,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"750GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"750GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"},magItemA:{quant:1,sides:1,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:1,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,table:"TableF",type:"Itens Mágicos"},magItemB:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"750GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,table:"TableF",type:"Itens Mágicos"},magItemB:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"},magItemA:{quant:1,sides:1,table:"TableF",type:"Itens Mágicos"},magItemB:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:1,table:"TableF",type:"Itens Mágicos"},magItemB:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"750GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:2,sides:4,table:"250GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:1,table:"TableI",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"500GP",type:"Gemas"},magItemA:{quant:1,sides:1,table:"TableI",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:1,table:"TableI",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:1,table:"TableI",type:"Itens Mágicos"}}];
export const hoard4=[{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:8,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:10,table:"2500GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:8,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:4,table:"7500GP",type:"Objetos de Arte "},magItemA:{quant:1,sides:8,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:8,table:"5000GP",type:"Gemas"},magItemA:{quant:1,sides:8,table:"TableC",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:6,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:10,table:"2500GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:4,table:"7500GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:8,table:"5000GP",type:"Gemas"},magItemA:{quant:1,sides:6,table:"TableD",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:6,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:10,table:"2500GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:6,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:4,table:"7500GP",type:"Objetos de Arte "},magItemA:{quant:1,sides:6,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:8,table:"5000GP",type:"Gemas"},magItemA:{quant:1,sides:6,table:"TableE",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"gem"},magItemA:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:10,table:"2500GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:4,table:"7500GP",type:"Objetos de Arte "},magItemA:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:8,table:"5000GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"gem"},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:10,table:"2500GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:4,table:"7500GP",type:"Objetos de Arte "},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:8,table:"5000GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableH",type:"Itens Mágicos"}},{gemArt:{quant:3,sides:6,table:"1000GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableI",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:10,table:"2500GP",type:"Objetos de Arte"},magItemA:{quant:1,sides:4,table:"TableI",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:4,table:"7500GP",type:"Objetos de Arte "},magItemA:{quant:1,sides:1,table:"TableF",type:"Itens Mágicos"},magItemB:{quant:1,sides:4,table:"TableG",type:"Itens Mágicos"}},{gemArt:{quant:1,sides:8,table:"5000GP",type:"Gemas"},magItemA:{quant:1,sides:4,table:"TableI",type:"Itens Mágicos"}}];
export const gem10=["Azurita","Ágata malhada ","Quartzo azul","Ágata ocular","Hematita","Lápis lazúli","Malaquita","Ágata musgo","Obsidiana","Rodocrosita","Olho de tigre","Turquesa"]
export const gem50=["Pedra de sangue","Cornalina","Calcedônia","Crisoprásio","Citrina","Jaspe","Pedra lunar","Ônix","Quartzo","Sardônica","Quartzo rosa estrela","Zircônio",]
export const gem100=["Âmbar","Ametista","Crisoberilo","Coral","Granada","Jade","Jato","Pérola","Espinela","Turmalina"]
export const gem500=["Alexandrita","Água-marinha","Pérola negra","Espinela azul","Peridoto","Topázio"]
export const gem1000=["Opala negra","Safira azul","Esmeralda","Opala de fogo","Opala","Rubi estrela","Safira estrela","Safira amarela"]
export const gem5000=["Safira negra","Diamante","Jacinto","Rubi"]
export const art25=["Jarro de prata","Estatueta esculpida em osso","Bracelete de ouro pequeno","Vestimenta de tecido dourado","Máscara de veludo negra costurada com fios de prata","Cálice de cobre com filigrana prateada","Par de dados de osso com gravuras","Pequeno espelho numa moldura de madeira pintada","Lenço de seda bordado","Broche de ouro com um retrato pintado dentro"]
export const art250=["Anel de ouro cravejado com pedras de sangue","Estatueta esculpida em marfim","Bracelete de ouro largo","Gargantilha de prata com um pingente de pedra preciosa","Coroa de bronze","Robe de seda com adornos de ouro","Grande tapeçaria elegante","Caneca de bronze com jades incrustadas","Caixa de miniaturas de animais em turquesa","Gaiola de pássaro de ouro com filigrana de electro"]
export const art750=["Cálice de prata cravejado com pedras da lua","Espada longa de lâmina prateada com conjunto de jatos no cabo","Harpa de madeira exótica com marfim incrustado e gemas de zircónio","Pequeno ídolo de ouro","Pente de ouro em formato de dragão cravejada com granadas vermelhas nos olhos","Rolha de garrafa gravada com folhas de ouro e cravejada com ametistas","Adaga de electro cerimonial com uma pérola negra no pomo","Broche de prata e ouro","Estatueta de obsidiana com detalhes e incrustações de ouro","Máscara de guerra de ouro pintada"]
export const art2500=["Corrente de ouro elegante cravejada com uma opala de fogo","Antiga pintura obra-prima","Manto de seda e veludo bordado com diversas pedras da lua cravejadas","Bracelete de platina cravejado com uma safira","Luvas bordadas com lascas de joias","Peúga cheia de joias","Caixa de música de ouro","Argola de ouro cravejada com quatro águasmarinhas","Tapa-olho com um olho falso cravejado em uma safira azul e uma pedra da lua","Um colar de pequenas pérolas rosas"]
export const art7500=["Coroa de ouro cheia de joias","Anel de platina cheio de joias","Pequena estatueta de ouro cravejada com rubis","Taça de ouro cravejada com esmeraldas","Caixa de joias de ouro com filigrana de platina","Sarcófago infantil de ouro pintado","Jogo de tabuleiro de jade com peças de ouro maciço","Chifre de marfim adornado com filigrana de ouro"]

export const tableA=[
    {value:"50GP",name:"Poção de cura",page:153},
    {value:"50GP",name:"Pergaminho de magia (truque)",page:197},
    {value:"50GP",name:"Poção de escalar",page:202},
    {value:"50GP",name:"Pergaminho de magia (1° nível)",page:197},
    {value:"50GP",name:"Pergaminho de magia (2° nível)",page:197},
    {value:"50GP",name:"Poção de cura maior",page:201},
    {value:"50GP",name:"Mochila de carga",page:194},
    {value:"50GP",name:"Globo de fluxo",page:187}
]
export const tableB=[
    {value:"50GP",name:"Poção de cura maior",page:201},
    {value:"50GP",name:"Poção de sopro de fogo",page:203},
    {value:"50GP",name:"Poção de resistência",page:203},
    {value:"50GP",name:"Munição +1",page:194},
    {value:"50GP",name:"Poção de amizade animal",page:201},
    {value:"50GP",name:"Poção de força do gigante da colina",page:202},
    {value:"50GP",name:"Poção de aumentar",page:201},
    {value:"50GP",name:"Poção de respirar na água",page:203},
    {value:"50GP",name:"Pergaminho de magia (2° nível)",page:197},
    {value:"50GP",name:"Pergaminho de magia (3° nível)",page:197},
    {value:"50GP",name:"Mochila de carga",page:194},
    {value:"50GP",name:"Unguento de Keoghtom",page:210},
    {value:"50GP",name:"Óleo escorregadio",page:195},
    {value:"50GP",name:"Pó do desaparecimento",page:201},
    {value:"50GP",name:"Pó da seca",page:201},
    {value:"50GP",name:"Pó de espirrar e tossir",page:200},
    {value:"50GP",name:"Gema elemental",page:186},
    {value:"50GP",name:"Filtro do amor",page:183},
    {value:"50GP",name:"Jarro de alquimia",page:187},
    {value:"50GP",name:"Capa de respirar na água",page:171},
    {value:"50GP",name:"Manto da arraia",page:191},
    {value:"50GP",name:"Globo de fluxo",page:187},
    {value:"50GP",name:"Óculos noturnos",page:203},
    {value:"50GP",name:"Elmo de compreensão de idiomas",page:177},
    {value:"50GP",name:"Bastão imóvel",page:163},
    {value:"50GP",name:"Lanterna de revelação",page:189},
    {value:"50GP",name:"Armadura do marinheiro",page:156},
    {value:"50GP",name:"Armadura de mitral",page:156},
    {value:"50GP",name:"Poção de envenenamento",page:202},
    {value:"50GP",name:"Anel de natação",page:153},
    {value:"50GP",name:"Robe dos itens úteis",page:205},
    {value:"50GP",name:"Corda de escalada",page:174},
    {value:"50GP",name:"Sela do cavaleiro",page:207},
    {value:"50GP",name:"Varinha de detectar magia",page:212},
    {value:"50GP",name:"Varinha de segredos",page:213},
]
export const tableC=[
    {value:"50GP",name:"Poção de cura maior",page:666},
    {value:"50GP",name:"Pergaminho de magia (4° nível)",page:666},
    {value:"50GP",name:"Munição +2",page:666},
    {value:"50GP",name:"Poção de clarividência",page:666},
    {value:"50GP",name:"Poção de encolher",page:666},
    {value:"50GP",name:"Poção de forma gasosa",page:666},
    {value:"50GP",name:"Poção de força do gigante do gelo",page:666},
    {value:"50GP",name:"Poção de força do gigante de pedra",page:666},
    {value:"50GP",name:"Poção de heroísmo",page:666},
    {value:"50GP",name:"Poção de invulnerabilidade",page:666},
    {value:"50GP",name:"Poção de ler mentes",page:666},
    {value:"50GP",name:"Pergaminho de magia (5° nível)",page:666},
    {value:"50GP",name:"Elixir de saúde",page:666},
    {value:"50GP",name:"Óleo de forma etérea",page:666},
    {value:"50GP",name:"Poção de força do gigante do fogo",page:666},
    {value:"50GP",name:"Pena de Quaal",page:666},
    {value:"50GP",name:"Pergaminho de proteção",page:666},
    {value:"50GP",name:"Saco de feijões",page:666},
    {value:"50GP",name:"Contas de força",page:666},
    {value:"50GP",name:"Carrilhão de abertura",page:666},
    {value:"50GP",name:"Decantador de água infinita",page:666},
    {value:"50GP",name:"Olhos de visão momentânea",page:666},
    {value:"50GP",name:"Barco dobrável",page:666},
    {value:"50GP",name:"Sacola prestativa de Heward",page:666},
    {value:"50GP",name:"Ferraduras da velocidade",page:666},
    {value:"50GP",name:"Colar de bolas de fogo",page:666},
    {value:"50GP",name:"Periapto de saúde",page:666},
    {value:"50GP",name:"Pedras de mensagem",page:666}
]
export const tableD=[
    {value:"50GP",name:"Poção de cura suprema",page:666},
    {value:"50GP",name:"Poção de invisibilidade",page:666},
    {value:"50GP",name:"Poção de velocidade",page:666},
    {value:"50GP",name:"Pergaminho de magia (6° nível)",page:666},
    {value:"50GP",name:"Pergaminho de magia (7° nível)",page:666},
    {value:"50GP",name:"Munição +3",page:666},
    {value:"50GP",name:"Óleo de precisão",page:666},
    {value:"50GP",name:"Poção de voo",page:666},
    {value:"50GP",name:"Poção de força do gigante das nuvens",page:666},
    {value:"50GP",name:"Poção de longevidade",page:666},
    {value:"50GP",name:"Poção de vitalidade",page:666},
    {value:"50GP",name:"Pergaminho de magia (8° nível)",page:666},
    {value:"50GP",name:"Ferraduras de zéfiro",page:666},
    {value:"50GP",name:"Pigmentos maravilhosos de Nolzur",page:666},
    {value:"50GP",name:"Bolsa devoradora",page:666},
    {value:"50GP",name:"Buraco portátil",page:666}
]
export const tableE=[
    {value:"50GP",name:"Pergaminho de magia (8° nível)",page:666},
    {value:"50GP",name:"Poção de força do gigante da tempestade",page:666},
    {value:"50GP",name:"Poção de cura suprema",page:666},
    {value:"50GP",name:"Pergaminho de magia (9° nível)",page:666},
    {value:"50GP",name:"Solvente universal",page:666},
    {value:"50GP",name:"Flecha assassina",page:666},
    {value:"50GP",name:"Cola soberana",page:666}
]
export const tableF=[
    {value:"50GP",name:"Arma +1",page:666},
    {value:"50GP",name:"Escudo +1",page:666},
    {value:"50GP",name:"Escudo sentinela",page:666},
    {value:"50GP",name:"Amuleto de proteção contra detecção e localização",page:666},
    {value:"50GP",name:"Botas élficas",page:666},
    {value:"50GP",name:"Botas de caminhar e saltar",page:666},
    {value:"50GP",name:"Braçadeiras de arquearia",page:666},
    {value:"50GP",name:"Broche do escudo",page:666},
    {value:"50GP",name:"Vassoura voadora",page:666},
    {value:"50GP",name:"Manto élfico",page:666},
    {value:"50GP",name:"Manto de proteção",page:666},
    {value:"50GP",name:"Manoplas de força do ogro",page:666},
    {value:"50GP",name:"Chapéu de disfarce",page:666},
    {value:"50GP",name:"Azagaia de relâmpago",page:666},
    {value:"50GP",name:"Pérola do poder",page:666},
    {value:"50GP",name:"Bastão guardião de pactos +1",page:666},
    {value:"50GP",name:"Sandálias de patas de aranha",page:666},
    {value:"50GP",name:"Cajado da víbora",page:666},
    {value:"50GP",name:"Cajado da píton",page:666},
    {value:"50GP",name:"Espada da vingança",page:666},
    {value:"50GP",name:"Tridente de comandar peixes",page:666},
    {value:"50GP",name:"Varinha de misseis mágicos",page:666},
    {value:"50GP",name:"Varinha do arcano de guerra +1",page:666},
    {value:"50GP",name:"Varinha de teia",page:666},
    {value:"50GP",name:"Arma de alerta",page:666},
    {value:"50GP",name:"Armadura de adamante (cota de malha)",page:666},
    {value:"50GP",name:"Armadura de adamante (camisão de malha)",page:666},
    {value:"50GP",name:"Armadura de adamante (brunea)",page:666},
    {value:"50GP",name:"Bolsa de truques (cinza)",page:666},
    {value:"50GP",name:"Bolsa de truques (ferrugem)",page:666},
    {value:"50GP",name:"Bolsa de truques (bronze)",page:666},
    {value:"50GP",name:"Botas do inverno",page:666},
    {value:"50GP",name:"Diadema da destruição",page:666},
    {value:"50GP",name:"Baralho das ilusões",page:666},
    {value:"50GP",name:"Garrafa da fumaça eterna",page:666},
    {value:"50GP",name:"Olhos do encantamento",page:666},
    {value:"50GP",name:"Olhos de águia",page:666},
    {value:"50GP",name:"Estátua de poderes incríveis (corvo de prata)",page:666},
    {value:"50GP",name:"Gema da luminosidade",page:666},
    {value:"50GP",name:"Luvas de apanhar projeteis",page:666},
    {value:"50GP",name:"Luvas de nadar e escalar",page:666},
    {value:"50GP",name:"Luvas do ladrão",page:666},
    {value:"50GP",name:"Tiara do intelecto",page:666},
    {value:"50GP",name:"Elmo de telepatia",page:666},
    {value:"50GP",name:"Instrumento dos bardos (alaúde de Doss)",page:666},
    {value:"50GP",name:"Instrumento dos bardos (bandolim de Fochlucan)",page:666},
    {value:"50GP",name:"Instrumento dos bardos (citara de Mac-Fuimidh)",page:666},
    {value:"50GP",name:"Medalhão de pensamentos",page:666},
    {value:"50GP",name:"Colar de adaptação",page:666},
    {value:"50GP",name:"Periapto da cicatrização",page:666},
    {value:"50GP",name:"Flauta assombrada",page:666},
    {value:"50GP",name:"Flauta dos esgotos",page:666},
    {value:"50GP",name:"Anel de saltar",page:666},
    {value:"50GP",name:"Anel de escudo mental",page:666},
    {value:"50GP",name:"Anel de calor",page:666},
    {value:"50GP",name:"Anel de andar na água",page:666},
    {value:"50GP",name:"Aljava de Ehlonna",page:666},
    {value:"50GP",name:"Pedra da boa sorte",page:666},
    {value:"50GP",name:"Leque do vento",page:666},
    {value:"50GP",name:"Botas aladas",page:666}
]
export const tableG=[
    {value:"50GP",name:"Arma +2",page:666},
    {value:"50GP",name:"Estátua de poderes incríveis",page:666},
    {value:"50GP",name:"Armadura de adamante (peitoral)",page:666},
    {value:"50GP",name:"Armadura de adamante (cota de talas)",page:666},
    {value:"50GP",name:"Amuleto de saúde",page:666},
    {value:"50GP",name:"Armadura de vulnerabilidade",page:666},
    {value:"50GP",name:"Escudo apanhador de flechas",page:666},
    {value:"50GP",name:"Cinto dos anões",page:666},
    {value:"50GP",name:"Cinturão de força do gigante da colina",page:666},
    {value:"50GP",name:"Machado furioso",page:666},
    {value:"50GP",name:"Botas de levitação",page:666},
    {value:"50GP",name:"Botas de velocidade",page:666},
    {value:"50GP",name:"Bacia de comandar elementais da água",page:666},
    {value:"50GP",name:"Braceletes de defesa",page:666},
    {value:"50GP",name:"Braseiro de comandar elementais do fogo",page:666},
    {value:"50GP",name:"Capa do saltimbanco",page:666},
    {value:"50GP",name:"Incensório de comandar elementais do ar",page:666},
    {value:"50GP",name:"Cota de malha +1",page:666},
    {value:"50GP",name:"Armadura da resistência (cota de malha)",page:666},
    {value:"50GP",name:"Camisão de malha +1",page:666},
    {value:"50GP",name:"Armadura da resistência (camisão de malha)",page:666},
    {value:"50GP",name:"Manto de deslocamento",page:666},
    {value:"50GP",name:"Manto do morcego",page:666},
    {value:"50GP",name:"Cubo de força",page:666},
    {value:"50GP",name:"Fortaleza instantânea de Daern",page:666},
    {value:"50GP",name:"Adaga de envenenamento",page:666},
    {value:"50GP",name:"Algemas dimensionais",page:666},
    {value:"50GP",name:"Matadora de dragões",page:666},
    {value:"50GP",name:"Malha élfica",page:666},
    {value:"50GP",name:"Língua flamejante",page:666},
    {value:"50GP",name:"Gema de visão",page:666},
    {value:"50GP",name:"Matador de gigantes",page:666},
    {value:"50GP",name:"Couro batido encantador",page:666},
    {value:"50GP",name:"Elmo de teletransporte",page:666},
    {value:"50GP",name:"Trombeta da destruição",page:666},
    {value:"50GP",name:"Trombeta do Valhalla (prata e latão)",page:666},
    {value:"50GP",name:"Instrumento dos bardos (mandolim de Canaith)",page:666},
    {value:"50GP",name:"Instrumento dos bardos (lira de Cli)",page:666},
    {value:"50GP",name:"Pedra iônica (prontidão)",page:666},
    {value:"50GP",name:"Pedra iônica (proteção)",page:666},
    {value:"50GP",name:"Pedra iônica (armazenamento)",page:666},
    {value:"50GP",name:"Pedra iônica (sustento)",page:666},
    {value:"50GP",name:"Faixas de ferro de Bilarro",page:666},
    {value:"50GP",name:"Armadura de couro +1",page:666},
    {value:"50GP",name:"Armadura de resistência (couro)",page:666},
    {value:"50GP",name:"Maça do rompimento",page:666},
    {value:"50GP",name:"Maça de destruição",page:666},
    {value:"50GP",name:"Maça do terror",page:666},
    {value:"50GP",name:"Manto de resistência à magia",page:666},
    {value:"50GP",name:"Corrente de contas de oração",page:666},
    {value:"50GP",name:"Periapto de proteção contra veneno",page:666},
    {value:"50GP",name:"Anel de cativar animais",page:666},
    {value:"50GP",name:"Anel de evasão",page:666},
    {value:"50GP",name:"Anel de queda suave",page:666},
    {value:"50GP",name:"Anel de ação livre",page:666},
    {value:"50GP",name:"Anel de proteção",page:666},
    {value:"50GP",name:"Anel de resistência",page:666},
    {value:"50GP",name:"Anel de armazenar magia",page:666},
    {value:"50GP",name:"Anel do aríete",page:666},
    {value:"50GP",name:"Anel de visão de raio-X",page:666},
    {value:"50GP",name:"Robe dos olhos",page:666},
    {value:"50GP",name:"Bastão da obediência",page:666},
    {value:"50GP",name:"Bastão guardião de pactos +2",page:666},
    {value:"50GP",name:"Corda de estrangulamento",page:666},
    {value:"50GP",name:"Brunea +1",page:666},
    {value:"50GP",name:"Armadura de resistência (brunea)",page:666},
    {value:"50GP",name:"Escudo +2",page:666},
    {value:"50GP",name:"Escudo de atração de projeteis",page:666},
    {value:"50GP",name:"Cajado de enfeitiçar",page:666},
    {value:"50GP",name:"Cajado de cura",page:666},
    {value:"50GP",name:"Cajado de enxame de insetos",page:666},
    {value:"50GP",name:"Cajado das florestas",page:666},
    {value:"50GP",name:"Cajado do definhamento",page:666},
    {value:"50GP",name:"Pedra de comandar elementais da terra",page:666},
    {value:"50GP",name:"Lâmina do sol",page:666},
    {value:"50GP",name:"Espada do furto de vidas",page:666},
    {value:"50GP",name:"Espada do sangramento",page:666},
    {value:"50GP",name:"Bastão do tentáculo",page:666},
    {value:"50GP",name:"Arma viciosa",page:666},
    {value:"50GP",name:"Varinha de obrigação",page:666},
    {value:"50GP",name:"Varinha de detecção de inimigos",page:666},
    {value:"50GP",name:"Varinha de medo",page:666},
    {value:"50GP",name:"Varinha de bolas de fogo",page:666},
    {value:"50GP",name:"Varinhas de relâmpagos",page:666},
    {value:"50GP",name:"Varinha de paralisia",page:666},
    {value:"50GP",name:"Varinha do arcano de guerra +2",page:666},
    {value:"50GP",name:"Varinha das maravilhas",page:666},
    {value:"50GP",name:"Asas voadoras",page:666}
]
export const tableH=[
    {value:"50GP",name:"Arma +3",page:666},
    {value:"50GP",name:"Amuleto dos planos",page:666},
    {value:"50GP",name:"Tapete voador",page:666},
    {value:"50GP",name:"Bola de cristal (versão muito rara)",page:666},
    {value:"50GP",name:"Anel de regeneração",page:666},
    {value:"50GP",name:"Anel de estrelas cadentes",page:666},
    {value:"50GP",name:"Anel de telecinésia",page:666},
    {value:"50GP",name:"Robe das cores cintilantes",page:666},
    {value:"50GP",name:"Robe das estrelas",page:666},
    {value:"50GP",name:"Bastão de absorção",page:666},
    {value:"50GP",name:"Bastão de prontidão",page:666},
    {value:"50GP",name:"Bastão de segurança",page:666},
    {value:"50GP",name:"Bastão guardião de pactos +3",page:666},
    {value:"50GP",name:"Cimitarra da velocidade",page:666},
    {value:"50GP",name:"Escudo +3",page:666},
    {value:"50GP",name:"Cajado do fogo",page:666},
    {value:"50GP",name:"Cajado do frio",page:666},
    {value:"50GP",name:"Cajado do poder",page:666},
    {value:"50GP",name:"Cajado de ataque",page:666},
    {value:"50GP",name:"Cajado de trovão e relâmpago",page:666},
    {value:"50GP",name:"Espada decepadora",page:666},
    {value:"50GP",name:"Varinha de metamorfose",page:666},
    {value:"50GP",name:"Varinha do arcano de guerra +3",page:666},
    {value:"50GP",name:"Armadura de adamante (meia-armadura)",page:666},
    {value:"50GP",name:"Armadura de adamante (placas)",page:666},
    {value:"50GP",name:"Escudo animado",page:666},
    {value:"50GP",name:"Cinturão de força do gigante do fogo",page:666},
    {value:"50GP",name:"Cinturão de força do gigante do frio (ou de pedra)",page:666},
    {value:"50GP",name:"Peitoral +1",page:666},
    {value:"50GP",name:"Armadura de resistência (peitoral)",page:666},
    {value:"50GP",name:"Vela da invocação",page:666},
    {value:"50GP",name:"Cota de malha +2",page:666},
    {value:"50GP",name:"Camisão de malha +2",page:666},
    {value:"50GP",name:"Manto da aranha",page:666},
    {value:"50GP",name:"Espada dançarina",page:666},
    {value:"50GP",name:"Armadura demoníaca",page:666},
    {value:"50GP",name:"Brunea de escamas de dragão",page:666},
    {value:"50GP",name:"Armadura anã",page:666},
    {value:"50GP",name:"Arremessador anão",page:666},
    {value:"50GP",name:"Garrafa do efreeti",page:666},
    {value:"50GP",name:"Estátua de poderes incríveis (corcel de obsidiana)",page:666},
    {value:"50GP",name:"Marca congelante",page:666},
    {value:"50GP",name:"Elmo brilhante",page:666},
    {value:"50GP",name:"Trombeta do Valhalla (bronze)",page:666},
    {value:"50GP",name:"Instrumento dos bardos (harpa de Anstruth)",page:666},
    {value:"50GP",name:"Pedra iônica (absorção)",page:666},
    {value:"50GP",name:"Pedra iônica (agilidade)",page:666},
    {value:"50GP",name:"Pedra iônica (fortitude)",page:666},
    {value:"50GP",name:"Pedra iônica (intuição)",page:666},
    {value:"50GP",name:"Pedra iônica (intelecto)",page:666},
    {value:"50GP",name:"Pedra iônica (liderança)",page:666},
    {value:"50GP",name:"Pedra iônica (força)",page:666},
    {value:"50GP",name:"Armadura de couro +2",page:666},
    {value:"50GP",name:"Manual da saúde corporal",page:666},
    {value:"50GP",name:"Manual do bom exercício",page:666},
    {value:"50GP",name:"Manual dos golens",page:666},
    {value:"50GP",name:"Manual da rapidez de movimentos",page:666},
    {value:"50GP",name:"Espelho do aprisionamento",page:666},
    {value:"50GP",name:"Ladra das nove vidas",page:666},
    {value:"50GP",name:"Arco do juramento",page:666},
    {value:"50GP",name:"Brunea +2",page:666},
    {value:"50GP",name:"Escudo de proteção contra magia",page:666},
    {value:"50GP",name:"Cota de talas +1",page:666},
    {value:"50GP",name:"Armadura de resistência (cota de talas)",page:666},
    {value:"50GP",name:"Armadura de couro batido +1",page:666},
    {value:"50GP",name:"Armadura de resistência (couro batido)",page:666},
    {value:"50GP",name:"Tomo dos grandes pensamentos",page:666},
    {value:"50GP",name:"Tomo de liderança e influência",page:666},
    {value:"50GP",name:"Tomo da compreensão",page:666}
]
export const tableI=[
    {value:"50GP",name:"Defensora",page:666},
{value:"50GP",name:"Martelo dos trovões",page:666},
{value:"50GP",name:"Lâmina da sorte",page:666},
{value:"50GP",name:"Espada de retaliação",page:666},
{value:"50GP",name:"Vingadora sagrada",page:666},
{value:"50GP",name:"Anel de invocação de djinni",page:666},
{value:"50GP",name:"Anel de invisibilidade",page:666},
{value:"50GP",name:"Anel de refletir magias",page:666},
{value:"50GP",name:"Bastão do grande poder",page:666},
{value:"50GP",name:"Cajado do arcano",page:666},
{value:"50GP",name:"Espada vorpal",page:666},
{value:"50GP",name:"Cinturão de força do gigante das nuvens",page:666},
{value:"50GP",name:"Peitoral +2",page:666},
{value:"50GP",name:"Cota de malha +3",page:666},
{value:"50GP",name:"Camisão de malha +3",page:666},
{value:"50GP",name:"Manto de invisibilidade",page:666},
{value:"50GP",name:"Bola de cristal (versão lendária)",page:666},
{value:"50GP",name:"Meia-armadura +1",page:666},
{value:"50GP",name:"Frasco de ferro",page:666},
{value:"50GP",name:"Armadura de couro +3",page:666},
{value:"50GP",name:"Armadura de placas +1",page:666},
{value:"50GP",name:"Robe do arquimago",page:666},
{value:"50GP",name:"Bastão de ressurreição",page:666},
{value:"50GP",name:"Brunea +1",page:666},
{value:"50GP",name:"Escaravelho da proteção",page:666},
{value:"50GP",name:"Cota de talas +2",page:666},
{value:"50GP",name:"Armadura de couro batido +2",page:666},
{value:"50GP",name:"Poço dos muitos mundos",page:666},
{value:"50GP",name:"Armadura mágica",page:666},
{value:"50GP",name:"Dispositivo de Kwalish",page:666},
{value:"50GP",name:"Armadura de invulnerabilidade",page:666},
{value:"50GP",name:"Cinturão de força do gigante da tempestade",page:666},
{value:"50GP",name:"Cubo do portal",page:666},
{value:"50GP",name:"Baralho das surpresas",page:666},
{value:"50GP",name:"Malha do efreeti",page:666},
{value:"50GP",name:"Armadura de resistência (meia-armadura)",page:666},
{value:"50GP",name:"Trombeta do Valhalla (ferro)",page:666},
{value:"50GP",name:"Instrumento dos bardos (harpa de Ollamh)",page:666},
{value:"50GP",name:"Pedra iônica (absorção maior)",page:666},
{value:"50GP",name:"Pedra iônica (maestria)",page:666},
{value:"50GP",name:"Pedra iônica (regeneração)",page:666},
{value:"50GP",name:"Armadura de placas da forma etérea",page:666},
{value:"50GP",name:"Armadura de placas da resistência",page:666},
{value:"50GP",name:"Anel de comandar elementais do ar",page:666},
{value:"50GP",name:"Anel de comandar elementais da terra",page:666},
{value:"50GP",name:"Anel de comandar elementais do fogo",page:666},
{value:"50GP",name:"Anel dos três desejos",page:666},
{value:"50GP",name:"Anel de comandar elementais da água",page:666},
{value:"50GP",name:"Esfera da aniquilação",page:666},
{value:"50GP",name:"Talismã da bondade pura",page:666},
{value:"50GP",name:"Talismã da esfera",page:666},
{value:"50GP",name:"Talismã do mal absoluto",page:666},
{value:"50GP",name:"Tomo da língua quieta",page:666}
]
// export const tableAA=[
//     "Poção de cura - LDM pg. 153",
//     "Pergaminho de magia (truque) - LDM pg. 197",
//     "Poção de escalar - LDM pg. 202",
//     "Pergaminho de magia (1° nível) - LDM pg. 197",
//     "Pergaminho de magia (2° nível) - LDM pg. 197",
//     "Poção de cura maior - LDM pg. 201",
//     "Mochila de carga - LDM pg. 194",
//     "Globo de fluxo - LDM pg. 187"
// ]
// export const tableBB=[
//     "Poção de cura maior - LDM pg. 201",
//     "Poção de sopro de fogo - LDM pg. 203",
//     "Poção de resistência - LDM pg. 203",
//     "Munição +1 - LDM pg. 194",
//     "Poção de amizade animal - LDM pg. 201",
//     "Poção de força do gigante da colina - LDM pg. 202",
//     "Poção de aumentar - LDM pg. 201",
//     "Poção de respirar na água - LDM pg. 203",
//     "Pergaminho de magia (2° nível) - LDM pg. 197",
//     "Pergaminho de magia (3° nível) - LDM pg. 197",
//     "Mochila de carga - LDM pg. 194",
//     "Unguento de Keoghtom - LDM pg. 210",
//     "Óleo escorregadio - LDM pg. 195",
//     "Pó do desaparecimento - LDM pg. 201",
//     "Pó da seca - LDM pg. 201",
//     "Pó de espirrar e tossir - LDM pg. 200",
//     "Gema elemental - LDM pg. 186",
//     "Filtro do amor - LDM pg. 183",
//     "Jarro de alquimia - LDM pg. 187",
//     "Capa de respirar na água - LDM pg. 171",
//     "Manto da arraia - LDM pg. 191",
//     "Globo de fluxo - LDM pg. 187",
//     "Óculos noturnos - LDM pg. 203",
//     "Elmo de compreensão de idiomas - LDM pg. 177",
//     "Bastão imóvel - LDM pg. 163",
//     "Lanterna de revelação - LDM pg. 189",
//     "Armadura do marinheiro - LDM pg. 156",
//     "Armadura de mitral - LDM pg. 156",
//     "Poção de envenenamento - LDM pg. 202",
//     "Anel de natação - LDM pg. 153",
//     "Robe dos itens úteis - LDM pg. 205",
//     "Corda de escalada - LDM pg. 174",
//     "Sela do cavaleiro - LDM pg. 207",
//     "Varinha de detectar magia - LDM pg. 212",
//     "Varinha de segredos - LDM pg. 213"
// ]
// export const tableCC=["Poção de cura maior - LDM pg. 201","Pergaminho de magia (4° nível) - LDM pg. 197","Munição +2 - LDM pg. 194","Poção de clarividência - LDM pg. ","Poção de encolher - LDM pg. ","Poção de forma gasosa - LDM pg. ","Poção de força do gigante do gelo - LDM pg. ","Poção de força do gigante de pedra - LDM pg. ","Poção de heroísmo - LDM pg. ","Poção de invulnerabilidade - LDM pg. ","Poção de ler mentes - LDM pg. ","Pergaminho de magia (5° nível) - LDM pg. 197","Elixir de saúde - LDM pg. ","Óleo de forma etérea - LDM pg. ","Poção de força do gigante do fogo - LDM pg. ","Pena de Quaal - LDM pg. ","Pergaminho de proteção - LDM pg. ","Saco de feijões - LDM pg. ","Contas de força - LDM pg. ","Carrilhão de abertura - LDM pg. ","Decantador de água infinita - LDM pg. ","Olhos de visão momentânea - LDM pg. ","Barco dobrável - LDM pg. ","Sacola prestativa de Heward - LDM pg. ","Ferraduras da velocidade - LDM pg. ","Colar de bolas de fogo - LDM pg. ","Periapto de saúde - LDM pg. ","Pedras de mensagem - LDM pg. "]
// export const tableDD=["Poção de cura suprema - LDM pg. ","Poção de invisibilidade - LDM pg. ","Poção de velocidade - LDM pg. ","Pergaminho de magia (6° nível) - LDM pg. 197","Pergaminho de magia (7° nível) - LDM pg. 197","Munição +3 - LDM pg. 194","Óleo de precisão - LDM pg. ","Poção de voo - LDM pg. ","Poção de força do gigante das nuvens - LDM pg. ","Poção de longevidade - LDM pg. ","Poção de vitalidade - LDM pg. ","Pergaminho de magia (8° nível) - LDM pg. 197","Ferraduras de zéfiro - LDM pg. ","Pigmentos maravilhosos de Nolzur - LDM pg. ","Bolsa devoradora - LDM pg. ","Buraco portátil - LDM pg."]
// export const tableEE=["Pergaminho de magia (8° nível) - LDM pg. 197","Poção de força do gigante da tempestade - LDM pg. ","Poção de cura suprema - LDM pg. ","Pergaminho de magia (9° nível) - LDM pg. 197","Solvente universal - LDM pg. ","Flecha assassina - LDM pg. ","Cola soberana - LDM pg. "]
// export const tableFF=["Arma +1 - LDM pg. ","Escudo +1 - LDM pg. ","Escudo sentinela - LDM pg. ","Amuleto de proteção contra detecção e localização - LDM pg. ","Botas élficas - LDM pg. ","Botas de caminhar e saltar - LDM pg. ","Braçadeiras de arquearia - LDM pg. ","Broche do escudo - LDM pg. ","Vassoura voadora - LDM pg. ","Manto élfico - LDM pg. ","Manto de proteção - LDM pg. ","Manoplas de força do ogro - LDM pg. ","Chapéu de disfarce - LDM pg. ","Azagaia de relâmpago - LDM pg. ","Pérola do poder - LDM pg. ","Bastão guardião de pactos +1 - LDM pg. ","Sandálias de patas de aranha - LDM pg. ","Cajado da víbora - LDM pg. ","Cajado da píton - LDM pg. ","Espada da vingança - LDM pg. ","Tridente de comandar peixes - LDM pg. ","Varinha de misseis mágicos - LDM pg. ","Varinha do arcano de guerra +1 - LDM pg. ","Varinha de teia - LDM pg. ","Arma de alerta - LDM pg. ","Armadura de adamante (cota de malha) - LDM pg. ","Armadura de adamante (camisão de malha) - LDM pg. ","Armadura de adamante (brunea) - LDM pg. ","Bolsa de truques (cinza) - LDM pg. ","Bolsa de truques (ferrugem) - LDM pg. ","Bolsa de truques (bronze) - LDM pg. ","Botas do inverno - LDM pg. ","Diadema da destruição - LDM pg. ","Baralho das ilusões - LDM pg. ","Garrafa da fumaça eterna - LDM pg. ","Olhos do encantamento - LDM pg. ","Olhos de águia - LDM pg. ","Estátua de poderes incríveis (corvo de prata) - LDM pg. ","Gema da luminosidade - LDM pg. ","Luvas de apanhar projeteis - LDM pg. ","Luvas de nadar e escalar - LDM pg. ","Luvas do ladrão - LDM pg. ","Tiara do intelecto - LDM pg. ","Elmo de telepatia - LDM pg. ","Instrumento dos bardos (alaúde de Doss) - LDM pg. ","Instrumento dos bardos (bandolim de Fochlucan) - LDM pg. ","Instrumento dos bardos (citara de Mac-Fuimidh) - LDM pg. ","Medalhão de pensamentos - LDM pg. ","Colar de adaptação - LDM pg. ","Periapto da cicatrização - LDM pg. ","Flauta assombrada - LDM pg. ","Flauta dos esgotos - LDM pg. ","Anel de saltar - LDM pg. ","Anel de escudo mental - LDM pg. ","Anel de calor - LDM pg. ","Anel de andar na água - LDM pg. ","Aljava de Ehlonna - LDM pg. ","Pedra da boa sorte - LDM pg. ","Leque do vento - LDM pg. ","Botas aladas - LDM pg. "]
// export const tableGG=["Arma +2 - LDM pg. ","Estátua de poderes incríveis - LDM pg. ","Armadura de adamante (peitoral) - LDM pg. ","Armadura de adamante (cota de talas) - LDM pg. ","Amuleto de saúde - LDM pg. ","Armadura de vulnerabilidade - LDM pg. ","Escudo apanhador de flechas - LDM pg. ","Cinto dos anões - LDM pg. ","Cinturão de força do gigante da colina - LDM pg. ","Machado furioso - LDM pg. ","Botas de levitação - LDM pg. ","Botas de velocidade - LDM pg. ","Bacia de comandar elementais da água - LDM pg. ","Braceletes de defesa - LDM pg. ","Braseiro de comandar elementais do fogo - LDM pg. ","Capa do saltimbanco - LDM pg. ","Incensório de comandar elementais do ar - LDM pg. ","Cota de malha +1 - LDM pg. ","Armadura da resistência (cota de malha) - LDM pg. ","Camisão de malha +1 - LDM pg. ","Armadura da resistência (camisão de malha) - LDM pg. ","Manto de deslocamento - LDM pg. ","Manto do morcego - LDM pg. ","Cubo de força - LDM pg. ","Fortaleza instantânea de Daern - LDM pg. ","Adaga de envenenamento - LDM pg. ","Algemas dimensionais - LDM pg. ","Matadora de dragões - LDM pg. ","Malha élfica - LDM pg. ","Língua flamejante - LDM pg. ","Gema de visão - LDM pg. ","Matador de gigantes - LDM pg. ","Couro batido encantador - LDM pg. ","Elmo de teletransporte - LDM pg. ","Trombeta da destruição - LDM pg. ","Trombeta do Valhalla (prata e latão) - LDM pg. ","Instrumento dos bardos (mandolim de Canaith) - LDM pg. ","Instrumento dos bardos (lira de Cli) - LDM pg. ","Pedra iônica (prontidão) - LDM pg. ","Pedra iônica (proteção) - LDM pg. ","Pedra iônica (armazenamento) - LDM pg. ","Pedra iônica (sustento) - LDM pg. ","Faixas de ferro de Bilarro - LDM pg. ","Armadura de couro +1 - LDM pg. ","Armadura de resistência (couro) - LDM pg. ","Maça do rompimento - LDM pg. ","Maça de destruição - LDM pg. ","Maça do terror - LDM pg. ","Manto de resistência à magia - LDM pg. ","Corrente de contas de oração - LDM pg. ","Periapto de proteção contra veneno - LDM pg. ","Anel de cativar animais - LDM pg. ","Anel de evasão - LDM pg. ","Anel de queda suave - LDM pg. ","Anel de ação livre - LDM pg. ","Anel de proteção - LDM pg. ","Anel de resistência - LDM pg. ","Anel de armazenar magia - LDM pg. ","Anel do aríete - LDM pg. ","Anel de visão de raio-X - LDM pg. ","Robe dos olhos - LDM pg. ","Bastão da obediência - LDM pg. ","Bastão guardião de pactos +2 - LDM pg. ","Corda de estrangulamento - LDM pg. ","Brunea +1 - LDM pg. ","Armadura de resistência (brunea) - LDM pg. ","Escudo +2 - LDM pg. ","Escudo de atração de projeteis - LDM pg. ","Cajado de enfeitiçar - LDM pg. ","Cajado de cura - LDM pg. ","Cajado de enxame de insetos - LDM pg. ","Cajado das florestas - LDM pg. ","Cajado do definhamento - LDM pg. ","Pedra de comandar elementais da terra - LDM pg. ","Lâmina do sol - LDM pg. ","Espada do furto de vidas - LDM pg. ","Espada do sangramento - LDM pg. ","Bastão do tentáculo - LDM pg. ","Arma viciosa - LDM pg. ","Varinha de obrigação - LDM pg. ","Varinha de detecção de inimigos - LDM pg. ","Varinha de medo - LDM pg. ","Varinha de bolas de fogo - LDM pg. ","Varinhas de relâmpagos - LDM pg. ","Varinha de paralisia - LDM pg. ","Varinha do arcano de guerra +2 - LDM pg. ","Varinha das maravilhas - LDM pg. ","Asas voadoras - LDM pg. "]
// export const tableHH=["Arma +3 - LDM pg. ","Amuleto dos planos - LDM pg. ","Tapete voador - LDM pg. ","Bola de cristal (versão muito rara) - LDM pg. ","Anel de regeneração - LDM pg. ","Anel de estrelas cadentes - LDM pg. ","Anel de telecinésia - LDM pg. ","Robe das cores cintilantes - LDM pg. ","Robe das estrelas - LDM pg. ","Bastão de absorção - LDM pg. ","Bastão de prontidão - LDM pg. ","Bastão de segurança - LDM pg. ","Bastão guardião de pactos +3 - LDM pg. ","Cimitarra da velocidade - LDM pg. ","Escudo +3 - LDM pg. ","Cajado do fogo - LDM pg. ","Cajado do frio - LDM pg. ","Cajado do poder - LDM pg. ","Cajado de ataque - LDM pg. ","Cajado de trovão e relâmpago - LDM pg. ","Espada decepadora - LDM pg. ","Varinha de metamorfose - LDM pg. ","Varinha do arcano de guerra +3 - LDM pg. ","Armadura de adamante (meia-armadura) - LDM pg. ","Armadura de adamante (placas) - LDM pg. ","Escudo animado - LDM pg. ","Cinturão de força do gigante do fogo - LDM pg. ","Cinturão de força do gigante do frio (ou de pedra) - LDM pg. ","Peitoral +1 - LDM pg. ","Armadura de resistência (peitoral) - LDM pg. ","Vela da invocação - LDM pg. ","Cota de malha +2 - LDM pg. ","Camisão de malha +2 - LDM pg. ","Manto da aranha - LDM pg. ","Espada dançarina - LDM pg. ","Armadura demoníaca - LDM pg. ","Brunea de escamas de dragão - LDM pg. ","Armadura anã - LDM pg. ","Arremessador anão - LDM pg. ","Garrafa do efreeti - LDM pg. ","Estátua de poderes incríveis (corcel de obsidiana) - LDM pg. ","Marca congelante - LDM pg. ","Elmo brilhante - LDM pg. ","Trombeta do Valhalla (bronze) - LDM pg. ","Instrumento dos bardos (harpa de Anstruth) - LDM pg. ","Pedra iônica (absorção) - LDM pg. ","Pedra iônica (agilidade) - LDM pg. ","Pedra iônica (fortitude) - LDM pg. ","Pedra iônica (intuição) - LDM pg. ","Pedra iônica (intelecto) - LDM pg. ","Pedra iônica (liderança) - LDM pg. ","Pedra iônica (força) - LDM pg. ","Armadura de couro +2 - LDM pg. ","Manual da saúde corporal - LDM pg. ","Manual do bom exercício - LDM pg. ","Manual dos golens - LDM pg. ","Manual da rapidez de movimentos - LDM pg. ","Espelho do aprisionamento - LDM pg. ","Ladra das nove vidas - LDM pg. ","Arco do juramento - LDM pg. ","Brunea +2 - LDM pg. ","Escudo de proteção contra magia - LDM pg. ","Cota de talas +1 - LDM pg. ","Armadura de resistência (cota de talas) - LDM pg. ","Armadura de couro batido +1 - LDM pg. ","Armadura de resistência (couro batido) - LDM pg. ","Tomo dos grandes pensamentos - LDM pg. ","Tomo de liderança e influência - LDM pg. ","Tomo da compreensão - LDM pg. "]
// export const tableII=["Defensora - LDM pg. ","Martelo dos trovões - LDM pg. ","Lâmina da sorte - LDM pg. ","Espada de retaliação - LDM pg. ","Vingadora sagrada - LDM pg. ","Anel de invocação de djinni - LDM pg. ","Anel de invisibilidade - LDM pg. ","Anel de refletir magias - LDM pg. ","Bastão do grande poder - LDM pg. ","Cajado do arcano - LDM pg. ","Espada vorpal - LDM pg. ","Cinturão de força do gigante das nuvens - LDM pg. ","Peitoral +2 - LDM pg. ","Cota de malha +3 - LDM pg. ","Camisão de malha +3 - LDM pg. ","Manto de invisibilidade - LDM pg. ","Bola de cristal (versão lendária) - LDM pg. ","Meia-armadura +1 - LDM pg. ","Frasco de ferro - LDM pg. ","Armadura de couro +3 - LDM pg. ","Armadura de placas +1 - LDM pg. ","Robe do arquimago - LDM pg. ","Bastão de ressurreição - LDM pg. ","Brunea +1 - LDM pg. ","Escaravelho da proteção - LDM pg. ","Cota de talas +2 - LDM pg. ","Armadura de couro batido +2 - LDM pg. ","Poço dos muitos mundos - LDM pg. ","Armadura mágica - LDM pg. ","Dispositivo de Kwalish - LDM pg. ","Armadura de invulnerabilidade - LDM pg. ","Cinturão de força do gigante da tempestade - LDM pg. ","Cubo do portal - LDM pg. ","Baralho das surpresas - LDM pg. ","Malha do efreeti - LDM pg. ","Armadura de resistência (meia-armadura) - LDM pg. ","Trombeta do Valhalla (ferro) - LDM pg. ","Instrumento dos bardos (harpa de Ollamh) - LDM pg. ","Pedra iônica (absorção maior) - LDM pg. ","Pedra iônica (maestria) - LDM pg. ","Pedra iônica (regeneração) - LDM pg. ","Armadura de placas da forma etérea - LDM pg. ","Armadura de placas da resistência - LDM pg. ","Anel de comandar elementais do ar - LDM pg. ","Anel de comandar elementais da terra - LDM pg. ","Anel de comandar elementais do fogo - LDM pg. ","Anel dos três desejos - LDM pg. ","Anel de comandar elementais da água - LDM pg. ","Esfera da aniquilação - LDM pg. ","Talismã da bondade pura - LDM pg. ","Talismã da esfera - LDM pg. ","Talismã do mal absoluto - LDM pg. ","Tomo da língua quieta - LDM pg. ",]



