export const names = [
    {
        race: "Firbolg",
        male: [
            "Urifir","Wranmaer","Thero","Crahice","Carzeiros","Yindan","Balvalur","Kelwarin","Perdithas","Thesandoral","Genpeiros","Ilimyar","Beijeon","Fenqen","Genxalim","Yinxidor","Daexalim","Zinxidor","Virlen","Norwarin","Kelzumin","Traro","Perbalar","Daelar","Ianhice","Kelren","Sarhice","Sarran","Perkas","Keaven","Waesfaren","Waesqen","Olobalar","Yinwraek","Lutoris","Erdithas","Zumhorn","Perren","Mortumal","Adzeiros","Vanorin","Fenren","Herpeiros","Raloydark","Tracan","Urisalor","Kelmaris","Gensalor","Perdan","Beiven","Petnan","Genric","Kelsandoral","Ilidan","Balmenor","Petmenor","Trayarus","Syltoris","Cradithas","Ilican","Qiceran","Luquinal","Adris","Ianquinal","Fenvalur","Zumdithas","Aeberos","Yelwraek","Carmyar","Genwraek","Mirajor","Fenlen","Qinneiros","Dorneiros","Aezeiros","Yellamin","Adpetor","Luwraek","Sylberos","Ianvalur","Genberos","Ergeiros","Erpetor","Heikian","Sarfaren","Uriwraek","Hermaris","Glynsandoral","Petmaris","Craqen","Qinmaer","Aeric","Zumberos","Luzumin","Crasalor","Omaxalim","Keaxalim","Waessalor","Petgeiros"
        ],
        female: [
            "Gilthana","Olaphyra","Zinvaris","Ravanala","Sylkalyn","Uriharice","Grezorwyn","Keydi","Xilthana","Vencaryn","Yeslee","Adna","Lorajyre","Lialynn","Liasatra","Qifina","Dalee","Reygwyn","Triswenys","Arayra","Daelee","Ulabanise","Miaphyra","Holadove","Trisgella","Ulawenys","Miamoira","Yllafiel","Fabanise","Torfina","Cairel","Wysaphine","Eilzana","Nerivyre","Quiphine","Miazana","Zylthyra","Phicyne","Yesqirelle","Fasatra","Grehana","Yesroris","Faelee","Orihana","Liabanise","Valwynn","Phiynore","Chaevaris","Quiwynn","Zyljyre","Sylgella","Encyne","Uristina","Sylwynn","Jorona","Zylna","Yllalynn","Reyrie","Keyynore","Helelana","Favaris","Jostina","Iarvaris","Wysasatra","Eilhana","Zylleth","Keyvaris","Torzorwyn","Neritris","Magcaryn","Zinthana","Torphine","Zylcaryn","Ulaxina","Aradi","Torbella","Liacaryn","Wynfiel","Caigella","Xilcaryn","Sylrieth","Daefina","Krisphine","Daphine","Valra","Presyra","Aragwyn","Holasatra","Phizorwyn","Yllabanise","Valstina","Caikrana","Eilgwyn","Neristina","Olahana","Sylroris"
        ],
        lastName:[

        ]
    },
    {
        race: "Meio-Orc",
        male: [
            "Chakub","Duffthug","Gollik","Zogstuf","Rok","Grimfang","Rokblorggor","Wortsnaga","Bagul","Naznob","Orknack","Mekuz","Throdrok","Wazgut","Heddrak","Ratnob","Ongne","Rotstuf","Thokgrim","Badsnik","Zugug","Mekskab","U","Durrot","Ronkros","Dakagob","Skargob","Mekbag","Ugskab","Sniknob","Grotshak","Snikgrub","Dakagrot","Snikgut","Skabgrim","Zogwort","Grotwort","Rotgob","Mekbad","Grumgor","Nubgrot","Dakagrod","Gobnob","Morgut","Wortrot","Snagagor","Nargog","Narstuf","Duffrunt","Rotgrim","Skarbad","Gobbog","Dregbad","Urtydreg","Waagob","Zoggog","Badbog","Wortgob","59.Nafflug","Ogsog","Nazzod","Nobstuf","Nazlug","Skabthug","Gorlug","Ugstuf","Skabrot","Zogrot","Naffgrod","Grimskab","Mor","Nubwort","Gorbag","Snagathug","Gutgrim","Brubgrod","Durrot","Durzod","Zodslag","Zodrot","Ogog","Uggob","Morog","Nubslag","Urtyarg","Snikgog","Wazurty","Og","Skumbog","Brublug","Snikgut","Rotuz","Magfug","Grotnob","Zodthug","Brubgob","Dreg","Zodgrot","Grumgul","Mekdreg","Gutfug","Mugteef","Urtyfug","Nobgrim","Nobork","Zognob","Grimrot","Gorslag","Nobgob","Dakaog","Gorbad","Skabuz","Ratork","Grumshak","Brubzod","Oggor","Skabgob","Grumarg","Ug","Snikuz","Durslag","Ratgor","Waateef","Nazsnik","Waznob","Grumbag","Zoggor","Mugskab","Mekgob","Wortthug","Nobbog","Snotfang","Magog","Wazgrub","Urtygul","Nobrot","Gobbag","Shakwort","Skarskab","Uzstuf","Brubog","Skarbog","Dregarg","Durrunt","Mugork","Grotog","Mekstuf","Horbog","Nevarth","Neldskar","Elbauthin","Conrunt","Dakath","Horgarg","Connak","Gaelrunt","Montagor","Akrunt","Elashor","Usunskar","Akkar","Hortog","Finrod","Erlgarg","Turgon","Nelgork","Uthorim","Herbog","Beleg","Nestbog","Elaran","Erlarunt","Herbalar","Usskaar","Horith","Erlathan","Neldor","Usunaar","Gael","Virjeon","Conall","Nesterin","Agis","Sudryl","Celeborn","Elanjar","Filvendor","Aeson","Dalyor","Elbereth","Neldbad","Dalkaar","Hornog","Snaabog","Rabiz","Sudbad","Celenog","Elanbad","Filvnog","Aesbad",


        ],
        female: [
            "Mursha","Naz","Maui","Nobfang","Duzhar","Naffurty","Buzum","Zoguz","Ta","Mekslag","Glugka","Nazgul","Bugsel","Mag","Nazsnaga","Nubbog","Nubshak","Magnob","Gobgul","Morskab","Skarsnaga","Grumshak","Mekbag","Skarsnaga","Naruz","Nazarg","Uzshak","Brubwort","Brubsnaga","Skarstuf","Shakfang","Urty","Wazfang","Maggor","Grumstuf","Wortshak","Magslag","Waafang","Mekarg","Meksog","Nubshak","Waa","Grimgrod","Wazslag","Nazfug","Nubfang","Nazgob","Mekbad","Snikbog","Zoguz","Nazgrub","Waawort","Torobog","Chichlandra","Trandbad","Akash","Vaalguz","Fraeya","Daegrub","Elwing","Aelbog","Waadhel","Aelinor","Ravabad","Daeondra","Tehlgrub","Hacathra","Gilbad","Gaelira","Purtbog","Alais","Reyzbad","Gilgalad","Tornog","Aredhel","Purtguz","Siirist","Raebog","Tehlmar","Zaltga","Thranduil","Gaelug","Ravaphine","Alaiszag","Vaalyun","Portnog","Raegel","Siirwort","Zaltarish","Silvnog","Raunaeril","Tehlnez","Vaegon","Gaelnog","Toross","Trandbad","Therona","Namez","Purtham","Pierneg","Silvyr","Sandez","Reysalor","Aquabad","Gwenog","Sudniz","Calez","Elbjar","Elenoss","Galeguz","Nuobad","Namgul","Halanaga","Thernaga","Torbad","Elenwe","Nuovis","Calarel","Keerskag","Gweyr","Urmbad","Blythswana","Violenog","Morwen","Thereng","Sheedra","Halanag","Llamryl","Blythnog","Doreah","Sheebad","Rubrae","Takanaga","Phaerl","Saeya","Halanaestra","Violen","Keerla","Celebrían","Urmicca","Gaarbad","Mernez","Arwbag","Rathnog","Daenez","Hameadnaga","Glorfinbad","Shandalog","Haalija","Zealnaga","Idril","Shandalnaga","Rathiain","Haalnag","Takari","Daenag","Mereena","Rathnez","Zeale","Hamdar","Axilia","Gaarnog","Shandalar","Baelnog","Keernaga","Glorfindel","Na","Glornag","Logshan","Rilid","Thanra","Karita","Reenog","Liaxnog","Gaarbad","Nogbael","Nagdae","Baelen","Starnog","Gaarbuck","Nogna","Badwen","Adrog","Hamada","Baelgaar","Gaarna","Staarnez","Daebael","Nognag","Starfang","Darthstang","Arwen","Adstang","Cauladra","Gaarfang","Hamstang","Hameada","Daena","Nogfang","Gaerradh"

        ],
        lastName:[

        ]
    },
];